### PR TITLE
Update scc-codestyle to 0.4.0

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

This change comes with rubocop 0.80.0. Because of the many new rules, I
regenerated the `.rubocop_todo.yml` to slowly incorporate the new
changes.

## Change Type

*Please select the correct option.*

- [x] **New Feature** (a non-breaking change which adds new functionality)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/131255/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c54f7330da818fa9f1dcb1340e4d85295d5e4737 into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131574/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8246dcc430b19bcb06a4e3d91b6c604ecdd0045e into 8a2d4c3b42841bcb2d5a63a2b1cbf74d47f7acb0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131738/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8246dcc430b19bcb06a4e3d91b6c604ecdd0045e into f68692072dc17f7a23a0ed00b94dea9a8f0beda0)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/132839/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into 79e90aaf46968ec89a74ff14b3269415eab499df)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132840/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into 11ab5adadb9679957a9a1a45dfa8420720df064c)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/132841/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into bea2a88b046943eff8f7bf90b352585c61847eaf)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132980/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into a42943aaa5aab41df37ae3c399065a5438898d0c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132981/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into 6fc1d330974b42765d6ee037f7d59ae28b824d85)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132982/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into 8a421d990f8b50d9582c16e2eda156eb576d4279)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133153/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 016a8b265f97d744704413a26ba0f74d184d950c into 009e6c36528eab860ec50a254724121ac9bf0236)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133158/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b21f3e9f9a4956d7c41ad383003fbf9d5f862866 into 6a75c0d7a7454f589213dce5c3717eea452847a4)

**Review by lcaparroz — APPROVED** [review]
LGTM :+1:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133160/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b21f3e9f9a4956d7c41ad383003fbf9d5f862866 into a2fcd86ff7393c57b4f1355061937ba4e599d1d4)

**Pull request merged**
