### PR TITLE
WIP: Add ansible docker deployment contribution

### PR DESCRIPTION
**Pull request by ngetahun**
## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/268798/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into 2e81b5e7069cf83042c01a209e084773b90a5fe7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/270030/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into 0a8b3e911428351421652ca1ca23c7eac9fd9952)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/270185/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into 6da777085d3e11b287c4ca4c04c52fc0ace65625)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/271328/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into b459ce39ef910fb0e8af43a684168cda12f980b4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/271356/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into d129e4abd17e7d65e94c86b96795f1b175b72478)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/274340/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into a8c0f780baa70ea14efd7f5c7a128e3c8872979a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/281418/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into 261c82e2da47ff6a603bf9a4209553751767bca8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/281422/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ce5ea195e84f13a1b0bbfab30239f87173e692c1 into 2b1a3993d4047af2139130afb3e35569d93c38c5)

**Comment by felixsch** [comment]
@ngetahun Do you still plan on finishing this? I wonder if this whole playbook is something we should push to galaxy if finished!

**Comment by felixsch** [comment]
@ngetahun I close this here for now. Since there was no movement until now!

**Pull request closed without merging**
