### PR TITLE
Change expired subscription validation

### PR DESCRIPTION
**Pull request by lcaparroz**
This PR is supposed to be merged as a fix to the current status of PR #819.

Currently, the validation of expired subscription in the RMT API happens
through a `before_action` hook in the subscriptions/systems route.
However, the solution brought some undesirable side-effects which would
require some effort to keep the current API compatibility.

With this commit, a new approach is proposed, which checks the
subscription expiration onlye when creating an activation in RMT, the
very moment a subscription is actually used to be associated to a
system.

### CODE REVIEW

**Comment by lcaparroz** [comment]
[[RDQ] Do not allow expired subscription to be used in RMT when registerering with a regcode](https://trello.com/c/hS96pTHM/2199-rdq-do-not-allow-expired-subscription-to-be-used-in-rmt-when-registerering-with-a-regcode)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226041/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 23f373be0b97abd6acd2cd8d6de9b00f3506b22e into e6a670ac776a521ffe1b30599328e1895038e986)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226126/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 23f373be0b97abd6acd2cd8d6de9b00f3506b22e into e6a670ac776a521ffe1b30599328e1895038e986)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226143/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 23f373be0b97abd6acd2cd8d6de9b00f3506b22e into e6a670ac776a521ffe1b30599328e1895038e986)

**Review by felixsch — APPROVED** [review]
lgtm :+1:

**How I reviewed this pull request:**

- Checked the changes for pontential improvements
- Run a test rmt and registered a active subscription to see if this still works
- Registered a system without a regcode to see if this still works
- Trying to register a system with a expired regcode to see it **not** working
- Register a system with an active subscription and expire it afterwards and check if the RMT still works for the system.

**As always, if you think I missed something I should test, please let me know!** :rocket:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/226227/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9508b124bdaaf160f07aa8777ac3e006d326b307 into e6a670ac776a521ffe1b30599328e1895038e986)

**Pull request merged**
