### PR TITLE
Raise an exception when there is an extension activated which has no migration successor

### PR DESCRIPTION
**Pull request by digitaltom**
## Description

This makes https://github.com/SUSE/happy-customer/pull/5256 available for RMT.

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          4 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/migration_engine.rb</td>
      <td>57</td>
      <td>Incorrect indentation detected (column 4 instead of 0).</td>
    </tr>
  </tbody>
</table></td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/migration_engine.rb</td>
      <td>58</td>
      <td>Incorrect indentation detected (column 0 instead of 4).</td>
    </tr>
  </tbody>
</table></td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/migration_engine.rb</td>
      <td>58</td>
      <td>Missing space after <code>#</code>. (https://rubystyle.guide#hash-space)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>spec/models/migration_engine_spec.rb</td>
      <td>281</td>
      <td>Name your test subject if you need to reference it explicitly. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/NamedSubject)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184204/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec73684093640e38ea5f9292a591ddd3e9a176b4 into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184205/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 6579800e959ce04430f22bff0200240657a22070 into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184247/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184249/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184266/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184328/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project rmt on step docker-compose-build-images. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project rmt on step docker-compose-build-images. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
Failed fast in project rmt on step docker-compose-build-images. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184342/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e873e59169359b8bacf2f2f29bb4c369173c30af into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>app/models/migration_engine.rb</td>
      <td>62</td>
      <td>Closing method call brace must be on the line after the last argument when opening brace is on a separate line from the first argument.</td>
    </tr>
  </tbody>
</table></td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>spec/requests/api/connect/v3/systems/products_controller_spec.rb</td>
      <td>498</td>
      <td>Align the elements of an array literal if they span more than one line. (https://rubystyle.guide#no-double-indent)</td>
    </tr>
  </tbody>
</table></td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184348/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 94f144dfe857cd0a47ff5911b3c0cc8553d40dba into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184362/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 94f144dfe857cd0a47ff5911b3c0cc8553d40dba into 57c3e24d3da0e80b114e74bfb86842e218b2f7ff)

**Review by Sergeykot — APPROVED** [review]
LGTM :+1:

**Pull request merged**
