### PR TITLE
[2/x] Add debian mirroring support to RMT

### PR DESCRIPTION
**Pull request by ngetahun**
This PR is part of our code sprint: https://trello.com/c/hU27QHob/3134-rdeb-sprint-tracker

**The whole changeset is:**

[[1/5] Prepare code sprint and implement repository type detection](https://github.com/SUSE/rmt/pull/1066)
[[2/5] Add flat debian mirroring support to RMT](https://github.com/SUSE/rmt/pull/1057)
[[3/5] Refactor suma mirroring](https://github.com/SUSE/rmt/pull/1059)
[[4/5] Refactor repomd mirroring](https://github.com/SUSE/rmt/pull/1060)
[[5/5] Fixes and cleanup](https://github.com/SUSE/rmt/pull/1067)
[[6/6] Nested debian repository support](https://github.com/SUSE/rmt/pull/1070)

**Implementations in this PR:**

- Creating a base class for mirroring repositories and add tests
- Implement Debian flat repository mirroring in its own class utilizing base class and write tests
- Improve `FileReference` class and make it a first class citizen in the code base

**How to review this pull request:**

*Test the new Debian mirroring implementation*
```ruby
$ bin/rails c
> debian = Repository.find_by(name: 'Debian-10-SUSE-Manager-Tools')
> mirror = RMT::Mirror::Debian.new(repository: debian, logger: RMT::Logger.new($stdout))
> mirror.mirror
# expect: this will download all debs of this repository

# In another terminal
$ tree <devrmt>/public/repo/SUSE/Updates/Debian/10-CLIENT-TOOLS/x86_64/update/
# expect: all debs are downloaded as in the original repository
# expect: metadata is existing in the directory

# back to the rails console
> mirror.mirror
# expect: It should not download any new packages only update timestamps
```

*Debian integration test*
```bash
# Terminal A
$ python3 -m http.server -d <devrmt>/public

# Terminal B
$ docker run --rm --network host -it debian:10
$ echo 'deb [trusted=yes allow-insecure=yes] http://0.0.0.0:8000/repo/SUSE/Updates/Debian/10-CLIENT-TOOLS/x86_64/update/ /' >> /etc/apt/sources.list
$ apt update
$ apt install spacecmd
# expect: It works! It is alive! It has a name! Its name is Herold!
```

**Thanks for reviewing this pull request!**

If you have any question please do not hesitate to approach me! :rocket:

**DO NOT MERGE UNTIL COMPLETELY READY**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349118/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 68e2bf55b98c57b3812ba3a7237ddf2a7e7641b6 into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349244/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 7ec14886dbe1e4136c8dd247adaa358589115e5e into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349258/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged cb882badd82a88503511edeed63c4c689f388a27 into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349406/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 58e0c7322f9f5a2620feaf1a5f9244781145b4e8 into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349437/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged dfea6488b698b535fcd794fb302c37dda00ae25d into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349439/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1f01b3603e1782975c6631a0df6dcdd9aea523e9 into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/349445/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1f01b3603e1782975c6631a0df6dcdd9aea523e9 into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350246/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 877b21ede451e62da6cf5eec8ec13ee69eac4234 into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350273/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged fda689229f6c3055f3dd512fb35db5838f1598c6 into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 0b4d39901b8b3f2c28e50a283bcfce4b5e1320de into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350445/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged de5a00ba6e2e08a4f5b7902b6bfb832ae495fc57 into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350446/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e5ab6b2bc8032213794bbf4e2ca471a23a6225c5 into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350453/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1680fa260426d6f9e673adf5924d45c695c84c3a into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/350457/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 35dbcac9e3de6862fd7a15fa978536a17c80a8ff into 98f1142f2bdc0a220c50f0d1c4dacfd51e30db49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351235/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 35dbcac9e3de6862fd7a15fa978536a17c80a8ff into 7e68170344b9747f53da348fea62e2668c3f2aee)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351236/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 76522acd889e19123cf523fbd441ab82341fdf35 into 7e68170344b9747f53da348fea62e2668c3f2aee)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351423/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 76522acd889e19123cf523fbd441ab82341fdf35 into 56477e726b7417f423f03cbc23ab8d5febc3b400)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351429/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b69bd0ae030660b47f1de51bbe0965ecc55054ed into 56477e726b7417f423f03cbc23ab8d5febc3b400)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351584/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b69bd0ae030660b47f1de51bbe0965ecc55054ed into 9f151f09811d94f59cf11460b814f1faa2f193c8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351594/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b69bd0ae030660b47f1de51bbe0965ecc55054ed into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351598/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e0a0eec67e9f55cb39a4e89aef5440ef0081a6aa into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/352210/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 018ac080d7b7505f93caa48febed3ef0880a304f into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/352239/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a8ea9c356a2816cd11f01199c6ba50bdfa73ceb9 into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/352372/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 75d9d835c8310a512de83154c0044a5fc32e342d into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/352887/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1efd7d95193eb6f0e9e379f9e111b7b60faaa307 into 91457227b05f9b2e7b124f0934f2008e32a9c4e0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/354752/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1efd7d95193eb6f0e9e379f9e111b7b60faaa307 into 024478b7c8a9b7c45d617377f2c472917220d603)

**Pull request merged**
