### PR TITLE
Added new pot files after proofreading

### PR DESCRIPTION
**Pull request by felixsch**
## Description

card: https://trello.com/c/wZ4PnOY9/1859-translation-round-ask-for-translations

**How to test the changes**:

There are no real changes for now. What you can do is incorporate the changes into the po files and check the in `bin/rmt-cli`

Thanks for reviewing!

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187263/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a341baa721b24f3bfa57e9f1dcf049ff8109f524 into c9a2c0a25899c58917d216fb150094001d39fb0b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187333/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a341baa721b24f3bfa57e9f1dcf049ff8109f524 into 05412b52a3cbaf2f3886fe77f84685d3f71aee40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187335/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a341baa721b24f3bfa57e9f1dcf049ff8109f524 into 9502b3b8b05e8c8cdfc60a0407605bde36495a36)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/187419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a341baa721b24f3bfa57e9f1dcf049ff8109f524 into 263421b2813012775fb532fc8a8c4a59b1a6a68d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187453/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a341baa721b24f3bfa57e9f1dcf049ff8109f524 into e7110f4096c8c8d2543dad907879adb25fd98b76)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/188037/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a341baa721b24f3bfa57e9f1dcf049ff8109f524 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/188353/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ca05d2336d6b248d3636ade67b71c8f18566ff55 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189522/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189683/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189696/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 771f28783396c9e4a5478bbf3825154110e96d86)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 4e784eb993d81d59161441fe6d3e4a26245e3f8b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189796/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 1fca334f0cd1b32d552e9e624754dce37c7a98ec)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189814/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 0c531f2ba87b5d1e61d17d0e6698a31a9218faf2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189815/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into 66c932025b24208ac1610fcb7f6672c482175e72)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/190294/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into a9b2e89e9e34d55178f94d480d3e40f49bee8470)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/190428/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04707a5e43d43c8523cd604acd3e3db067984709 into a9b2e89e9e34d55178f94d480d3e40f49bee8470)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/190432/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 83216ff334f1576fa020d8fee9c398efc8992a1c into a9b2e89e9e34d55178f94d480d3e40f49bee8470)

**Pull request merged**
