### PR TITLE
Add foreign keys that were missing from schema.rb

### PR DESCRIPTION
**Pull request by digitaltom**
## Description

It seems those foreign_key definitions were not committed before when they got introduced with a migration. 

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184065/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f2bb75ad00e456bb4fc7b1130c6d78194894510d into 023f61747d6a2b527cbc0ac4f0a83d9845a423a3)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184105/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f2bb75ad00e456bb4fc7b1130c6d78194894510d into 0aeb5c6fab7f7cde97e4fd59ff030b3fccfe59de)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184203/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f2bb75ad00e456bb4fc7b1130c6d78194894510d into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184362/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f2bb75ad00e456bb4fc7b1130c6d78194894510d into 57c3e24d3da0e80b114e74bfb86842e218b2f7ff)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184363/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f2bb75ad00e456bb4fc7b1130c6d78194894510d into fec62a0d6c4adf73863ad1ad841abef1a8e6c4ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/186264/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into fec62a0d6c4adf73863ad1ad841abef1a8e6c4ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187263/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into c9a2c0a25899c58917d216fb150094001d39fb0b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187333/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into 05412b52a3cbaf2f3886fe77f84685d3f71aee40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187335/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into 9502b3b8b05e8c8cdfc60a0407605bde36495a36)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/187419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into 263421b2813012775fb532fc8a8c4a59b1a6a68d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187453/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into e7110f4096c8c8d2543dad907879adb25fd98b76)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/188037/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ab3f1ed8564dea5e45371f139c4ba0017fbe2ff5 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/188386/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5114e5417616e84136330a4d4ba81bc553035299 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189557/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5114e5417616e84136330a4d4ba81bc553035299 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189565/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5114e5417616e84136330a4d4ba81bc553035299 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189683/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5114e5417616e84136330a4d4ba81bc553035299 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189696/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5114e5417616e84136330a4d4ba81bc553035299 into 771f28783396c9e4a5478bbf3825154110e96d86)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5114e5417616e84136330a4d4ba81bc553035299 into 4e784eb993d81d59161441fe6d3e4a26245e3f8b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189795/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2c0004783cd2bd637cabcdc7bb7c35b62605fad5 into 4e784eb993d81d59161441fe6d3e4a26245e3f8b)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189796/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c8b498395bc2903f6518678e6a9df6db5440e96f into 1fca334f0cd1b32d552e9e624754dce37c7a98ec)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189814/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 245742c2e6daa64e4e807ea54f09c01668240dc8 into 0c531f2ba87b5d1e61d17d0e6698a31a9218faf2)

**Pull request merged**
