### PR TITLE
Move CLI Initializers

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

Our previous location for initializers was confusing and it was easy not
to know where they were. Instead, to make it more clear, let's move the
initializers to config/initalizers_cli.

## Change Type

*Please select the correct option.*

- [x] **New Feature** (a non-breaking change which adds new functionality)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/131309/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 024fa3be9876dc871875f864ec0e1d162483c538 into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131574/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 21ca6264340c7f69adc83e73d03ec7f96655ac50 into 8a2d4c3b42841bcb2d5a63a2b1cbf74d47f7acb0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131738/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 21ca6264340c7f69adc83e73d03ec7f96655ac50 into f68692072dc17f7a23a0ed00b94dea9a8f0beda0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132839/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 21ca6264340c7f69adc83e73d03ec7f96655ac50 into 79e90aaf46968ec89a74ff14b3269415eab499df)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132840/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 21ca6264340c7f69adc83e73d03ec7f96655ac50 into 11ab5adadb9679957a9a1a45dfa8420720df064c)

**Pull request merged**
