### PR TITLE
Provider name can change, so make it case-insensitive

### PR DESCRIPTION
**Pull request by jesusbv**
## Description
Provider name can change, so make it case-insensitive

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [X] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/297490/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 49bfdb43845ee234666d0a1d705b8dcf740d99a0 into e54da1b4500fddaa684869a1204a9d425b11154d)

**Review by felixsch — APPROVED** [review]
lgtm :+1:

**Review by digitaltom — APPROVED** [review]

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/298811/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 49bfdb43845ee234666d0a1d705b8dcf740d99a0 into 47f1685a38ffceb892469c9e640afc848b5e63b0)

**Comment by digitaltom** [comment]
@jesusbv do you want to merge this?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/298818/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into 47f1685a38ffceb892469c9e640afc848b5e63b0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/298860/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into ecf699d0d093ee80b60035422c1d773abed5adc3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/301440/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into 093d44593717b3aa60430eb94a1971eb21894cb0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/301453/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into 7da59f7862eafc5804c9d6e4c92b5bdf340d3b9a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/301572/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into 451dace5bf13f776b732a2e1c1a1dc111e9b912c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/301575/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into ec9c46b298bc36b51d3e0ce55d63ccb5062af50f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/301577/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into 43e31dd03365e6ce712e04b6800de7bc3b4bc58f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/302235/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e25357124aced1cdf6d41acbc91896734703d33 into c5cedbbb50bfadc7f9ec1c224c0f6278c6fa3e46)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/302241/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 31a703c884b7c70abce4e16638ea0bc957ba886d into c5cedbbb50bfadc7f9ec1c224c0f6278c6fa3e46)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/302275/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 31a703c884b7c70abce4e16638ea0bc957ba886d into 8224d0e7163b46e85b6eeef4ffaca0b7a4039848)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/303401/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f014cc2f1f0c708d70c11e95651b5d870ae73e9e into 1c93250e48bf04035a1b370cf9af18f355e86155)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/303402/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f014cc2f1f0c708d70c11e95651b5d870ae73e9e into 5b182b04475c35d502ffcc1a8944a0b58e127055)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/303410/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f014cc2f1f0c708d70c11e95651b5d870ae73e9e into 8772bf72d921e92205c95387516472be4b75e379)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/305606/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 270fe85abd7f420f6e3177647e89dbf2cfc2b9f8 into facde22380a42d042f13dd42d9b931f77f732c24)

**Pull request merged**
