### PR TITLE
Add Ruby3.0 to test matrix

### PR DESCRIPTION
**Pull request by digitaltom**
## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/238606/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 30cbbd46c28fa4f9fd353478cdd33c24b86e1c81)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240057/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 70a6550f2244474da8848ab49f0ca2e55dbe1bc4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240536/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 8c4553d761653f359c40c0802e8467e8b414596d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240560/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into c1a3c5b7b2eae5343d70f029e1154331ed447e6e)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240651/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 9a138413e0dfee3008a477858111cd804752ef25)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240655/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 676099d07631ecff2814aaddc0d75765687f3224)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240656/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 62e174c483011213c57514b5fc5603ee0f2d1bc2)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240828/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 2822b51bb0d857e45d8570b58181295a088967fc)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240957/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into ed7c9a254224656d333d9e01309c93f56dca4a5a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/241752/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 8776d78d74db14b124a14650baeed30f44b00cca)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/241924/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into f365152aba8ffdcb8ebba4cf7f2d7137ab42d53b)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/242070/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into cf82866246db34eebe5383a0107a3a7973db7101)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/242887/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into d1da0a4fbafe8d1b7835d52948dd49b5cbd10e69)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/242912/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 226eeb6a7f6496c9f862d709ed98a3d4030e415f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/243032/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 515ad1001ed55f6a137c70c2305aa51608d150a1)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/243221/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 5dbcee4396cca0d81ea891ab8fa35a9051e4a403)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/243864/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 0a9c71a5e3e5a0bc13fa1ce3e92404fa83827f05)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/245183/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 54e5d3688349130e46aee3bedc9900e0087dcb3e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/245505/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 039e69e647aa496cb29275cb23042218122efd85)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/245506/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into c95985a223f3d51fb5373d888648abefae1b598b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249654/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 555a4b5ea3c4163ab58f0abb775fdb1dd7caeeea)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249678/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 629a8744c940df8cf3dfe3b8e3d0fc1f203c7cec into 30d9834cc7b5b22658035be97bea635419d65a2b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249679/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 048298f5333cf884c1bb1d5aa1c6008dcb571621 into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/250137/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 57ace4b550c508b68cca6f497c666abbf11bb225 into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/250138/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 18bfd491ce26f09f8e470217bdcbadf7d122c0ab into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/250141/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged fe28fd9f4a35c90498e1236432565d87d88c23e7 into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/250287/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged ca193c5af167f54d241b61e04e98e62b4c78c52d into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/250290/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8e794f2164577f0077bf9c028e781057b694bf7a into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/250816/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/252140/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into b89b8d137cd61b8a7da0c01c7f5a73d5b3754833)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/254530/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into ce2325855246f8d9bf64a374ef5597a8c5b41dc7)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/254558/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into e1ba12c592c15f4f23401aaa1c9b31e62296cc2c)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/255632/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into c1ea57ba3c654075a14c59a440ee84ef6e0a548d)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/259150/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into e99c2074d720fc3ee796cdb3ddac299344b41990)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/259508/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1e408f2ffac692a46ef5c3ab57607209b73de419 into 454855918e87bc5de7d526e497708e2e57e75488)

**Comment by felixsch** [comment]
@digitaltom @ngetahun Do you remember what is missing here? It looks like it still make sense to get this merged right?

**Comment by felixsch** [comment]
Close this in favor of: https://github.com/SUSE/rmt/pull/934

**Pull request closed without merging**
