### PR TITLE
Added a pull request template

### PR DESCRIPTION
**Pull request by tmuntaner**
# Description

Let's provide a pull request template to RMT so that we show the basic requirements for an RMT PR and make it easier for reviewers to understand changes and the motivation behind them.

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/127425/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4c7581c4aa44cf4384ba5b14f7e2c0c0dd2a3815 into 9c849995f4c3770d6406ae85abcfc8fdbc2729d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/127426/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1da843876a7314ec26b395730a24a0e3bae3b9f6 into 9c849995f4c3770d6406ae85abcfc8fdbc2729d4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/127606/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1da843876a7314ec26b395730a24a0e3bae3b9f6 into 9c849995f4c3770d6406ae85abcfc8fdbc2729d4)

**Review by ngetahun — COMMENTED** [review]
Shouldn't the file name be `PULL_REQUEST_TEMPLATE.md`? Source: https://github.blog/2016-02-17-issue-and-pull-request-templates/

**Comment by tmuntaner** [comment]
@ngetahun not according to the docs https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository.

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
