### PR TITLE
Update translation files for RMT

### PR DESCRIPTION
**Pull request by felixsch**
## Description
card: https://trello.com/c/DHweOiE9/1972-translation-round-finishing-touches

This pull request adds the new translated strings from weblate to RMT.

**How to review:**
Checkout the branch and run the `rmt-cli` and check the output using different languages `env LANG <lang> bin/rmt-cli`. Make sure the output looks okay and nothing is broken.

Please let me know if there is anything you need help with :)

## Note to myself: **DO NOT DELETE THE BRANCH AFTER MERGING**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/200685/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d7dedc7f43de358a4cfae8eb549485bff93825d1 into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger-pr">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202269/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7336ee6da111503592d6ca9c0ab4fe6b49dbb391 into 9228f9da8667575db38b9cab33b6596cf035a340)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/202284/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 7336ee6da111503592d6ca9c0ab4fe6b49dbb391 into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Comment by felixsch** [comment]
do we need a version bump here?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202733/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7336ee6da111503592d6ca9c0ab4fe6b49dbb391 into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202741/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 08ec0922c441c0e1e1620a3dd18bb095508ba7f4 into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Review by ngetahun — APPROVED** [review]
LGTM! tried it with `de` locale.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202764/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 08ec0922c441c0e1e1620a3dd18bb095508ba7f4 into 7d8d070c942fd90d6e39d55a0a4600d472ec9f59)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202784/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 08ec0922c441c0e1e1620a3dd18bb095508ba7f4 into e249c059d27e400450264e8ba5d981ce4132e4fc)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202788/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 59b9067ac2630ab5e659c2da98976a8bdf417fcf into e249c059d27e400450264e8ba5d981ce4132e4fc)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202886/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 59b9067ac2630ab5e659c2da98976a8bdf417fcf into 50e5c7c3d9b1f94b3b3ea4d9a35ceaceffa5cef5)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/203044/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged dfc2bb13a52ce59a7ed0a21315ab12b486b1a1f0 into 50e5c7c3d9b1f94b3b3ea4d9a35ceaceffa5cef5)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/203045/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 84a804ecb51ec33038c0cd4ecb28652f795d64f2 into 50e5c7c3d9b1f94b3b3ea4d9a35ceaceffa5cef5)

**Pull request merged**
