### PR TITLE
Mirror individual products/repos

### LINKED ISSUE #364: Support selection of repository/product in `rmt-cli mirror`
There are situations where it can be useful to be able to specify which repository or product to mirror in `rmt-cli mirror`. For example when you have a huge list of products to be mirrored, but just want one of them to get refreshed quickly. 

For example: `rmt-cli mirror repo <repo_id>` or `rmt-cli mirror product <product_id>`

### PR DESCRIPTION
**Pull request by ikapelyukhin**
By popular demand :slightly_smiling_face:
Closes #364.

Implements `rmt-cli mirror` subcommands, e.g.:

```
rmt-cli mirror all
rmt-cli mirror repository 1 2 3
rmt-cli mirror product 1 2 3
rmt-cli mirror product identifier/version/arch
```

`rmt-cli mirror` has `all` as the default task.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/24242/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 893694509321b8d91a2707a0dcd9535629965e09 into 4edba880d0f2e1278b0ad9bf9c9ed69877706baf)

**Comment by josegomezr** [comment]
Just a quick note, if I do pass two or more repo/product id and it fails in the middle of the process it will abort the whole mirroring process.

I think this could be improved in a future PR. For this I see a good initial mirroring behavior.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/26228/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 14474f21e2b31189af870a8357436ee856a5f5f9 into aedec045647eda619d348bd64932e4e0a70f384a)

**Comment by ikapelyukhin** [comment]
@josegomezr mirroring exceptions are being handled everywhere in a similar fashion now.

**Pull request merged**
