### PR TITLE
Added strings from proofreading

### PR DESCRIPTION
**Pull request by jmammen**
## Description

Added string from the latest proofreading.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/228175/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5358d4c23ec98f122c436bd4b6159f2e62a28425 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/228180/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

**How I reviewed this pull request:**

- Checked the xls files what changes are required
- Looked at the changes in the code

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229195/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229400/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229401/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229408/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/229411/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/229668/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ac80fc84848de92f25c18617a274be82bb4826af into 985ca90384875e9a19b2ec79d5529f3741da4e07)

**Pull request merged**
