### PR TITLE
cli: standardize the naming for --non-interactive

### PR DESCRIPTION
**Pull request by mssola**
## Description

In other places we are using `-n | --non-interactive`, and this is consistent with other SUSE tools such as zypper. Let's use these strings everywhere.

### CODE REVIEW

**Review by lcaparroz — APPROVED** [review]
LGTM

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240827/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2e238ccd18cf30509d9e906f86c1ee56d183277a into 62e174c483011213c57514b5fc5603ee0f2d1bc2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240828/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2e238ccd18cf30509d9e906f86c1ee56d183277a into 2822b51bb0d857e45d8570b58181295a088967fc)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240829/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a2ecbb1aabda35f1457ae7beeb159b870720c3c7 into 2822b51bb0d857e45d8570b58181295a088967fc)

**Comment by mssola** [comment]
Closing in favor of some work being done by @felixsch

**Pull request closed without merging**
