### PR TITLE
Protect Against Changing SCC Repo URLs

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

If SCC repositories changed their URLs, RMT had issues. This is because we expect scc_id to be unique, and with a new URL, it tries to create a new repository with the same scc_id. Instead of finding by the URL for SCC repositories, we can find by scc_id instead and avoid this issue.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/139137/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c918e2166cb8118d8af2fa72d1886729afcac542 into 8611a3d5b19d8a3ea3bef671fb5c4b05defad8c1)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/139180/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged cea6babb8be186c431087f12716ec1a089d003a0 into 8611a3d5b19d8a3ea3bef671fb5c4b05defad8c1)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/139353/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged cea6babb8be186c431087f12716ec1a089d003a0 into b6fafd48b69278d3ec13deec72d48082e67346a4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/139357/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged cea6babb8be186c431087f12716ec1a089d003a0 into b7f895aae2d12863d7317680e9f627b955f37efd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/140455/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged cea6babb8be186c431087f12716ec1a089d003a0 into 9d33134d3320908e0dc42fc80e50adef23c2b6ac)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/140458/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4666391a1c0db6481358676b68895d98175bc85c into 2586e915469448e7646e71d34297e3f1fa82d5df)

**Review by lcaparroz — APPROVED** [review]
LGTM, great work :+1:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/140696/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged bb010526a8301b91d5835cbcaa7797aef2401859 into 2586e915469448e7646e71d34297e3f1fa82d5df)

**Pull request merged**
