### PR TITLE
Add support for mirroring individual custom repositories on the CLI

### PR DESCRIPTION
**Pull request by doccaz**
This implements the feature described in issue #490.

I added a subcommand to the "mirror" function, so it's consistent with the already existing mirror command.

Example:
`# rmt-cli mirror custom repository 1248`

### CODE REVIEW

**Comment by doccaz** [comment]
Are the code coverage tests failing because it needs more unit tests for this new option?

**Comment by ikapelyukhin** [comment]
> Are the code coverage tests failing because it needs more unit tests for this new option?

Yes. Currently `lib/rmt/cli/mirror_custom.rb` has no test coverage. If you want to check coverage reports for yourself -- they are generated in `coverage/index.html` in the project working directory when you run `rake test`.

**Comment by doccaz** [comment]
I wrote the code coverage test (based on the existing mirror_spec.rb) and it appears to be running without errors. Is that correct?

**Comment by ikapelyukhin** [comment]
> I wrote the code coverage test (based on the existing mirror_spec.rb) and it appears to be running without errors. Is that correct?

Yep. That's a Codeclimate warning, don't worry about it. Travis pipeline is green. :+1:

**Comment by doccaz** [comment]
Is anything missing on this one?

**Comment by digitaltom** [comment]
Hi @doccaz, we have the review of this planned as part of our current RMT sprint.

**Comment by tmuntaner** [comment]
Thanks for your contribution, but the team decided to implement this requested feature in a slightly different way.

Please see PR #630 for the implementation.

**Pull request closed without merging**
