### PR TITLE
Change integration tests to test ruby versions 2.5.8 and 2.5.9

### PR DESCRIPTION
**Pull request by felixsch**
This will fail when we reach the point, when we start support other
version we need to think about how to handle this anyway.

Lets go easy for now.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger-pr">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/203223/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4674d17ed3d06bde1ccb391998263ad8f5fc053b into 5dde35e84f00d3d7307a896d195004f6fd559dd7)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/204216/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 4674d17ed3d06bde1ccb391998263ad8f5fc053b into 832dc2a5f42ecfdc4685d3b9edef6ed6a088e59f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204219/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4674d17ed3d06bde1ccb391998263ad8f5fc053b into 001ab0e468a32425593d2e8b6908cc5ebcadc2ae)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204340/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e5fc7c014af7c16df4e3f3283bef88df46236501 into 001ab0e468a32425593d2e8b6908cc5ebcadc2ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204344/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e5fc7c014af7c16df4e3f3283bef88df46236501 into 50fda87badf8d6354c4f23a32ca5ecad95259564)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204347/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d44dd99366239320051a194137490ee405f92c6e into 50fda87badf8d6354c4f23a32ca5ecad95259564)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204357/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d44dd99366239320051a194137490ee405f92c6e into b98281bf68312cb6d70a4871f64293c739b38e85)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204358/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d44dd99366239320051a194137490ee405f92c6e into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/205300/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d44dd99366239320051a194137490ee405f92c6e into 3b37b497194bb510a371c7ac507bb121287c1b92)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/205416/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d44dd99366239320051a194137490ee405f92c6e into ff29f420dbeb52ccb5559785805c096314b56ac4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/206227/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d44dd99366239320051a194137490ee405f92c6e into 5d1dbe0cd8dddf94d32e826818ae627d6a2f4cfc)

**Comment by felixsch** [comment]
This is already in place since @ngetahun fixed the danger implementation! Close this now!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/206377/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 484def649741550ee71104e9f44ed08f96213e19 into 5d1dbe0cd8dddf94d32e826818ae627d6a2f4cfc)

**Pull request merged**
