### PR TITLE
Change strong migration settings & add it to test

### PR DESCRIPTION
**Pull request by Sergeykot**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>config/initializers/strong_migrations.rb</td>
      <td>1</td>
      <td>Style/NumericLiterals: Use underscores(_) as decimal mark and separate every 3 digits with them. (https://github.com/bbatsov/ruby-style-guide#underscores-in-numerics)</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/76931/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 82dd4d6483094d5852a6e3f91e8aade7ba72de0b into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/76947/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 82dd4d6483094d5852a6e3f91e8aade7ba72de0b into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/77147/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 82dd4d6483094d5852a6e3f91e8aade7ba72de0b into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/77153/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 52cd14e6f1a1c2f372e3822d77c0bee07ac9ff4f into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/77168/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 52cd14e6f1a1c2f372e3822d77c0bee07ac9ff4f into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/77171/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 52cd14e6f1a1c2f372e3822d77c0bee07ac9ff4f into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/77183/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 52cd14e6f1a1c2f372e3822d77c0bee07ac9ff4f into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/77201/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 9a6273fb7b515d2d7a26a47a22ab01ca49b0426c into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/77203/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9a6273fb7b515d2d7a26a47a22ab01ca49b0426c into 678277a97835a95cac5a0260a0456bb33e703f65)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/77204/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 48a1f034975bdd588175302b8f9f0b0a7ada2b0b into 678277a97835a95cac5a0260a0456bb33e703f65)

**Pull request merged**
