### PR TITLE
Run integration tests through Prophet

### PR DESCRIPTION
**Pull request by Sergeykot**
This PR makes integration tests run and post comment to a PR with results of the pipeline

Please make sure to run tests locally with `no-cache`: 

```
docker-compose -f docker-compose-test.yml build
docker-compose -f docker-compose-test.yml run rmt_test ./integration/run.sh
```

Package `obs-service-format_spec_file` was missing when building Docker containers with `--no-cache` option. I had to activate 2 products to fix it.

also OBS `source_validator` complains if there is untracked tarball. So that I added command `osc addremove` to fix that.

**I will squash last 2 (or 3) commits into 1 after review**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          6 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>10</td>
      <td>Lint/CircularArgumentReference: Circular argument reference - <code>project</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>41</td>
      <td>Style/SymbolProc: Pass <code>&amp;:status</code> as an argument to <code>all?</code> instead of a block.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>102</td>
      <td>Style/SymbolProc: Pass <code>&amp;:status</code> as an argument to <code>all?</code> instead of a block.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>106</td>
      <td>Style/InverseMethods: Use <code>reject</code> instead of inverting <code>select</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>1</td>
      <td>Lint/ScriptPermission: Script file prophet.rb doesn’t have execute permission.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>10</td>
      <td>Style/MutableConstant: Freeze mutable objects assigned to constants.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          7 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>10</td>
      <td>Lint/CircularArgumentReference: Circular argument reference - <code>project</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>41</td>
      <td>Style/SymbolProc: Pass <code>&amp;:status</code> as an argument to <code>all?</code> instead of a block.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>102</td>
      <td>Style/SymbolProc: Pass <code>&amp;:status</code> as an argument to <code>all?</code> instead of a block.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>106</td>
      <td>Style/InverseMethods: Use <code>reject</code> instead of inverting <code>select</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>1</td>
      <td>Lint/ScriptPermission: Script file prophet.rb doesn’t have execute permission.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>10</td>
      <td>Style/MutableConstant: Freeze mutable objects assigned to constants.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>12</td>
      <td>Lint/LiteralAsCondition: Literal <code>true</code> appeared as a condition.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/355/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 49ce1700a91bfc84f0e99d74256d5efc0aba345e into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          7 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>10</td>
      <td>Lint/CircularArgumentReference: Circular argument reference - <code>project</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>41</td>
      <td>Style/SymbolProc: Pass <code>&amp;:status</code> as an argument to <code>all?</code> instead of a block.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>102</td>
      <td>Style/SymbolProc: Pass <code>&amp;:status</code> as an argument to <code>all?</code> instead of a block.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/ci_executor.rb</td>
      <td>106</td>
      <td>Style/InverseMethods: Use <code>reject</code> instead of inverting <code>select</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>1</td>
      <td>Lint/ScriptPermission: Script file prophet.rb doesn’t have execute permission.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>10</td>
      <td>Style/ExpandPathArguments: Use <code>expand_path('options-local.yml', __dir__)</code> instead of <code>expand_path('../options-local.yml', __FILE__)</code>.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>12</td>
      <td>Lint/LiteralAsCondition: Literal <code>true</code> appeared as a condition.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/356/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c18ec83b4bcce8a781b66e5188e5a8310ad6fd98 into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>1</td>
      <td>Lint/ScriptPermission: Script file prophet.rb doesn’t have execute permission.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>integration/prophet/prophet.rb</td>
      <td>1</td>
      <td>Lint/ScriptPermission: Script file prophet.rb doesn’t have execute permission.</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/358/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 4726c953ed3e2d8ff65cd59c34904f98fb80458b into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/359/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f106efe5f2e819429ed5925130755f87f4664ba8 into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/360/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged e7c34ddf3f247fda76691d5e361c4ec044505ed7 into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/364/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 48149ba5228195676f503152831d781b9f1faa1d into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/365/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 48149ba5228195676f503152831d781b9f1faa1d into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/366/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged b3e8e0de28013b0efc87728dfebb9264936fb682 into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/367/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 342663a7ea8c1c1d2b1d92af9ff0380682d81753 into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/368/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c60a47666a33582dc6b93ebceff5507303d81487 into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/369/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c4a6cc1e9932a3efe6633395255d2e94a8ba5950 into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/370/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged bdfd326e620674f5daed3ceee03357e82481819f into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/371/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 402b82fed304740c08013e256eff75be9eb43c9e into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Pull request merged**
