### PR TITLE
Replace outdated deeplink with link to SCC landing URL

### PR DESCRIPTION
**Pull request by thutterer**
The `/organization` route in SCC doesn't exist anymore.
Also we should avoid linking to specific routes as they might change.
Linking to just SCC should be enough to guide the user where the credentials can be found.

## Change Type

Trivial update of CLI output.

## Notes for reviewer

- Blank your `scc` credentials in your local config file.
- I think this change is trivial enough to not require a changelog update. Do you agree?

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164695/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 95936a47d593c70ed1e490ff1d8b402c3f82b762 into 9ca15bf4c6f6088efb8908145b0f54d3ab13079a)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164699/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 95936a47d593c70ed1e490ff1d8b402c3f82b762 into 9ca15bf4c6f6088efb8908145b0f54d3ab13079a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164702/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 95936a47d593c70ed1e490ff1d8b402c3f82b762 into 9ca15bf4c6f6088efb8908145b0f54d3ab13079a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164712/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 95936a47d593c70ed1e490ff1d8b402c3f82b762 into 9ca15bf4c6f6088efb8908145b0f54d3ab13079a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164719/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged e41a1937d73792478013fb4573f497c0a61cc61a into 30126a8db26f20e6059a1a1ba5dc7d30e4c5552e)

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

**How I tested this pull request**:
- I set invalid credentials in `/etc/rmt.conf` and checked the output containing `https://scc.suse.com` instead of `https://scc.suse.com/organization`.

**As always, if you think I missed something I should test, please let me know**

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/164732/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e41a1937d73792478013fb4573f497c0a61cc61a into 30126a8db26f20e6059a1a1ba5dc7d30e4c5552e)

**Pull request merged**
