### PR TITLE
support: migrated to supportconfig.rc

### PR DESCRIPTION
**Pull request by mssola**
## Description

ALP will not support the deprecated scplugin.rc framework. This commit, then, migrates our support script to work with supportconfig.rc.

This patch has been originally contributed by Jason Record on the linked Bugzilla entry.

Fixes bsc#1216389

## How to demo

**NOTE**: I have tested the following on a SLES15 SP4 machine. It would be extra dope if you could test it on other environments such as SLES12 LTSS.

The easiest route is to either install RMT on a machine, or re-use an existing installation. Thus, before any of this, ensure that `rmt-server` and `supportutils` are installed on your system. Then just copy the `support/rmt` file from this PR into `/usr/lib/supportconfig/plugins` and give it executable rights (as root):

```
# cp <path>/support/rmt /usr/lib/supportconfig/plugins/
# chmod +x /usr/lib/supportconfig/plugins/rmt
```

To ensure that the installation works, run `supportconfig` like so:

```
# supportconfig -F
```

There should be `prmt` (the 'p' is just a prefix for 'plugin'). You could try running just this plugin:

```
# supportconfig -i prmt
```

On the generated tarball, make sure that there is a file named `output-rmt.txt` with the results from this run.

Note that stuff like passwords have been blanked out by `supportconfig.rc`, this is to be expected. As a reference, this is the configuration as shown from my machine:

```
database:
  host: localhost
  database: rmt
  username: rmt
  password: *REMOVED BY SUPPORTCONFIG*
  adapter: mysql2
  encoding: utf8
  timeout: 5000
  pool: 5
```

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by mssola** [comment]
[Bug 1216389 - The supportconfig rmt plugin is using a deprecated library](https://trello.com/c/z1i3B6zD/3087-bug-1216389-the-supportconfig-rmt-plugin-is-using-a-deprecated-library)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/348118/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 29d042a069ea94aa0426a2c4dab6394bd4319d38 into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/348776/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a72344d7eb71fdc8af9cbe4b63e1f4d09ac4be2a into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Review by ngetahun — APPROVED** [review]
LGTM

**Pull request merged**
