### PR TITLE
Also add currently installed modules to the solution tree when doing …

### PR DESCRIPTION
**Pull request by jmammen**
…an offline migration.

Example:

Offline migration:
HPC15sp2 + NVIDIA compute module -> HPC15sp3 + NVIDIA compute module

The NVIDIA compute module stays installed, because it is compatible with both HPC15sp2 + HPC15sp3

## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/182660/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c590c73641a012c355b08b9dd9a7af26232dd256 into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/182692/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 949b6e663f0d7712999c85c37c469138e324a8b0 into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/182697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7e18841f117efa81042f2ac451a0542bbfb030ca into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/183802/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 01c8f79e03a8f3e8942ccb8b8cd53937cdd717c6 into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Review by digitaltom — APPROVED** [review]

**Pull request merged**
