### PR TITLE
Disable authentication for license files

### PR DESCRIPTION
**Pull request by rjschwei**
## Description

We want to have a where the client, for example SUSEConnect, can display license information to the user prior to registering a specific module or product. With the intend to have this display prior to registration the license file to be displayed cannot be in a path that requires authentication. Update the nginx configuration for Public Cloud setup to skip authentication for the license path.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [x ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/353953/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c7cb42cfd9f1f6c711a102120ceeb1cbc0d19bd7 into 91457227b05f9b2e7b124f0934f2008e32a9c4e0)

**Comment by digitaltom** [comment]
@jesusbv does this make https://github.com/SUSE/rmt/blob/master/engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb#L19 obsolete?

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

**How I reviewed this pull request:**

- Checked the nginx configuration changes
- Read about the `log_not_found` option which was new to me

**As always, if you think I missed something I should test, please let me know**:rocket:

**Comment by felixsch** [comment]
Can I merge this to allow it to be released with `2.15`? @rjschwei @jesusbv

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/354752/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged bf344c335d4cc0309f07e35890bff99c23b74b87 into 024478b7c8a9b7c45d617377f2c472917220d603)

**Comment by rjschwei** [comment]
> Can I merge this to allow it to be released with `2.15`? @rjschwei @jesusbv

@felixsch from my perspective yes. However, based on what @digitaltom found https://github.com/SUSE/rmt/blob/master/engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb#L19 this configuration change shouldn't be necessary. I think we should understand why the escape for authentication for the license path doesn't work already.

**Comment by jesusbv** [comment]
> @jesusbv does this make https://github.com/SUSE/rmt/blob/master/engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb#L19 obsolete?

Yes, the auth error happened before reaching that code

**Comment by rjschwei** [comment]
OK, I think we have all the answers now. @felixsch can you please merge? We can have a conversation about whether or not we want to remove https://github.com/SUSE/rmt/blob/master/engines/strict_authentication/app/controllers/strict_authentication/authentication_controller.rb#L19  i and that can be handled in a separate PR. Hope this approach is amenable to everyone. Thanks

**Comment by felixsch** [comment]
sounds good! Will merge this PR when CI is green!

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/356056/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged 625191eb427957f32761392fc77277c83ea2069b into ecf5efb3d9dbfce20f8d302a5ae4db03e08f611d)

**Pull request merged**
