### PR TITLE
Bump to version 2.7.1

### PR DESCRIPTION
**Pull request by lcaparroz**
## Description

Bump RMT to version 2.7.1

## Change Type

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226348/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Review by digitaltom — APPROVED** [review]

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226485/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226638/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/226804/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229412/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229492/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229654/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229668/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into 985ca90384875e9a19b2ec79d5529f3741da4e07)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/230312/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 64d081ce4d153cf09ddcc78c8b33b35e5cab75f9 into dea8b243bba218abb1aeaee61314bc495306cc7a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/230313/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a43667315ecfa361a7ef39ffd640133622c71be5 into 3f63bd1910985b7577633ab446fa50a810fcdf50)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/230448/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a43667315ecfa361a7ef39ffd640133622c71be5 into 3050b76d4cdbc26f60b3131a310b072bc3b38a7e)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/230615/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a43667315ecfa361a7ef39ffd640133622c71be5 into 9492a7c54ad245e8232f0a49c26415e886e9bfbb)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/231449/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a43667315ecfa361a7ef39ffd640133622c71be5 into 1b12c2a4302d462b116d8dcc33a87b6b30a216f1)

**Pull request merged**
