### PR TITLE
Fix RMT jenkins integration tests

### PR DESCRIPTION
**Pull request by digitaltom**
## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/254522/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 674b494bf514c1250a124d5fa9c4c4de2c67592a into b89b8d137cd61b8a7da0c01c7f5a73d5b3754833)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/254524/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4bc8b84492a55c59e8ac053f32ab0a21106d69d9 into b89b8d137cd61b8a7da0c01c7f5a73d5b3754833)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/254525/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d0bc901a6c67c26f4efd1ffdf7c216323debb605 into b89b8d137cd61b8a7da0c01c7f5a73d5b3754833)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
