### PR TITLE
Additional debug output for 'mirror' command

### PR DESCRIPTION
**Pull request by digitaltom**
* Additional debug output for 'mirror' command to see timestamps
* CLI debug output can get enabled from config file

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204066/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c1af2e6c81e3c81ce5266cabeaaa91a9ad0726d3 into 5dde35e84f00d3d7307a896d195004f6fd559dd7)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/204069/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 7ecc71bc36a4606be735b1bdad424e6a99423326 into 5dde35e84f00d3d7307a896d195004f6fd559dd7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204074/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 84d55c31c6a12e86e7fb0705d92065a00ca10074 into 5dde35e84f00d3d7307a896d195004f6fd559dd7)

**Review by lcaparroz — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204216/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 84d55c31c6a12e86e7fb0705d92065a00ca10074 into 832dc2a5f42ecfdc4685d3b9edef6ed6a088e59f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204217/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3802b8377b97d6a481a9784260860a97e1a2264a into 832dc2a5f42ecfdc4685d3b9edef6ed6a088e59f)

**Pull request merged**
