### PR TITLE
Fix scope overriding private AR method warning

### PR DESCRIPTION
**Pull request by Sergeykot**
Fixes https://github.com/SUSE/rmt/issues/165

The scope seems not to be used anywhere in the code

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by ikapelyukhin** [comment]
What happens in glue? Also probably needs a comment explaining why the enum key was renamed.

**Comment by fschueller** [comment]
`kind: 'test'` is used in `glue` in `subscriptions.rake` like so: https://github.com/SUSE/happy-customer/blob/28bb7bac5c6425e8b9593747d11f9ed77acaa0a4/glue/lib/tasks/subscriptions.rake#L212

Maybe better to be consistent there.

**Comment by Sergeykot** [comment]
@ikapelyukhin comment added. checking how it works in glue

**Comment by Sergeykot** [comment]
the issue does not exist in `glue` btw

**Pull request merged**
