### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by digitaltom**
Add link to OBS

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/79052/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c390d4e2bed9afefed83b15a1e22dbfc7d07ed33 into 72143eb869fbce724b25f2a0d9cc4acc3877a992)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/81380/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c390d4e2bed9afefed83b15a1e22dbfc7d07ed33 into 196ac9281c2ab202cfd504ad2354987d2180b589)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/81516/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c390d4e2bed9afefed83b15a1e22dbfc7d07ed33 into b9895aa88c86a6407428f5c1550b5ceb17d10a1b)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89493/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c390d4e2bed9afefed83b15a1e22dbfc7d07ed33 into dd0c0a37502c02934cc12f4274657eee425243b8)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89495/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c390d4e2bed9afefed83b15a1e22dbfc7d07ed33 into dd0c0a37502c02934cc12f4274657eee425243b8)

**Pull request merged**
