### PR TITLE
Fix secrets file access mode

### PR DESCRIPTION
**Pull request by ngetahun**
## Description
Set group readable permissions to rails credentials file.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351440/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8cfa26fe9e8db9e05eb67ae75b64688b453ac9b7 into 56477e726b7417f423f03cbc23ab8d5febc3b400)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351441/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 112067d07ef8d0989ec0d5b8e5677b2a34e53b3f into 40dd490a960f56cb2b641696bf5495eace3a8a7d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351558/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d358a4e8055f30728945eb36bd344d96fdbce08a into 40dd490a960f56cb2b641696bf5495eace3a8a7d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351584/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d358a4e8055f30728945eb36bd344d96fdbce08a into 9f151f09811d94f59cf11460b814f1faa2f193c8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/351594/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d358a4e8055f30728945eb36bd344d96fdbce08a into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by felixsch** [comment]
fixed here: https://github.com/SUSE/rmt/pull/1064
and feature removed here: https://github.com/SUSE/rmt/pull/1065

**Pull request closed without merging**
