### PR TITLE
Use headers metadata

### PR DESCRIPTION
**Pull request by jesusbv**
## Description

SUMa prefers use of headers, similar behaviour as SCC endpoints

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [X] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [X] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/320966/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f35395f5c6899d4701061f8c3b375906ff906e19 into 4232f5c99611c0615ac908afe99393f841bea4f6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/320967/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 29b367c30fd6ba571b1873daae4ca450997e4167 into 4232f5c99611c0615ac908afe99393f841bea4f6)

**Comment by digitaltom** [comment]
Did this get verified with a SUMA test instance?

**Comment by jesusbv** [comment]
> Did this get verified with a SUMA test instance?

Yes, SUMa team feedback is positive about this changes

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/321272/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 168229995c613d214ee5458e2098a20310e65043 into 7229597a95eb0c8b40a03e75523a9dd1626bd0b7)

**Pull request merged**
