### PR TITLE
Update scc-codestyle to 0.4.1

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

Update scc-codestyle to version 0.4.1

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [x] **New Feature** (a non-breaking change which adds new functionality)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133173/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged fae49266615f3541cd41f0d4704cf504242c3057 into 154b4647295367f221fbfb3f1cfef21feb21b3f2)

**Review by lcaparroz — COMMENTED** [review]
LGTM :+1:

**Review by lcaparroz — APPROVED** [review]
LGTM :+1:

**Pull request merged**
