### PR TITLE
Add git to Dockerfile

### PR DESCRIPTION
**Pull request by ikapelyukhin**
I've forked `vcr` gem, it fails to install in docker image without git.

### CODE REVIEW

**Comment by sandrew** [comment]
I believe you need only `git-core`

**Comment by tmuntan1** [comment]
@sandrew Sorry, I loaded the pull request before you added your message. Looking into that now as well.

**Comment by tmuntan1** [comment]
@sandrew You were right, it also works with `git-core` instead.

**Comment by ikapelyukhin** [comment]
@sandrew @tmuntan1 :+1:

**Pull request merged**
