### PR TITLE
Set permissions to run rmt-cli in the docker image.

### PR DESCRIPTION
**Pull request by jmammen**
I followed the [https://github.com/SUSE/rmt#running-with-docker-compose](guide) to setup RMT in a docker image. The problem was that I couldn't execute the rmt-cli because of missing permissions. This PR should fix this issue by setting the permissions.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/10447/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 7553c206aa57cf337573648dfae47e4e49469521)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/13007/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into f06fa3c8d156af25e5bac0eb8afd66ef719d8921)

**Comment by ikapelyukhin** [comment]
https://github.com/SUSE/rmt/blob/5b12ebc81d149e5abad79f9c8d48b681a5526de0/Dockerfile#L1

This docker container is severely outdated -- it could use some additional love :-)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/15330/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 0f0459635cd7756df430ae881b79a8bdabe96a29)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16422/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into f4541f3c3ebd0748cbc9855eeb809e1b7efc84b1)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16423/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 009b9270481fba7b92ccbab1c4003036085c8986)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16424/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 3230fd7b0523b7e4bc418a7a7e36f35c767af060)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16601/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 1d5c857ded8044b438e30168a690eade350caf94)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16602/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 620cf4399432ba23c19a068ccb67ba8bdf81a443)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16603/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 3d0ef46c729781df839e7e6af124fd5b0596b8c8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/17979/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into e2040903bafead90a1391149df7d67689fafe6d7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/19409/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into bb75ba256a592e515923185b439cd0d90c5fa5ef)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/19609/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 9ec6a0b5e61a19fa155a506e16465fc28de543ad)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/20086/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 84e430d21a2b26b91c4e8d2047b523394387ff0b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/20355/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 681726c953d85f3e18e0b75e42fee47c1bde1884)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/20958/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b12ebc81d149e5abad79f9c8d48b681a5526de0 into 91d6acfeb147ed22f8c56925a025c783c6c32156)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/22663/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 693d596ed6f4cc70926579506e7261d55ca0b52c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/23984/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 2068a292cb3e1b817e13686924be61b999e5bc98)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/23985/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 4edba880d0f2e1278b0ad9bf9c9ed69877706baf)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/24551/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 4f88790abe678261fd18ab7bbf5f406fbbb95022)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/25109/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into aedec045647eda619d348bd64932e4e0a70f384a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/26237/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into c3f08faab0a653be9e9bee235c1d06de59a6c404)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/27850/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 08dc218277f3de45b9a0aeacb20f9aabcfbbe568)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/28388/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 5c6f612f02fe2060d0d6397085117d8db3297d06)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/30642/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 0ac1fede23c33e37e4a53c65bdb8ef967d4e55d8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/30666/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into af954e7ab2e7c06acda971c43d1fadc1ad2aea49)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/30861/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 19f5cca80e366893aeadef3463cb55baebd1ac4d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/32016/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into f049c5e3966dfcdb82ad58d0d372f6f8bbdf9da9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/32847/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 26579ae19d01aaf495e247ccb3a7acd17864bc33)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/33702/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into fe2fbcbe0f8816ebc464f4b5b5177dcb75d13e45)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/33968/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into a4cbabc72adfa072ac4088d06ed181abdf5b5646)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/36016/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 65012a49b2eb4895fe13f75cf6bb8d5f922ed6ad)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/41700/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 8f712fa20596f95b25202ad6f80669838778c17f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/41707/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into fccde027d04befdb7d07cc72cd23fa55f6dcaa7d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/41711/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 378ba9732f56fead1e1d1fd10ea5b4294191e201)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/44558/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 8223a4beb0d62ed620f2cd4543e26a63a41c5cf8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/49962/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into ed117304ce57fa70fa8a2ff39d1fdb46a2d2033e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/49963/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 42c11448ef28e414ae06a54e3814199e15463e4a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/57809/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 4c5ecd3dc1d4939b80cbed2dd49e0f8339618de8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/57810/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 78e7cffe8edce873f793d5b1fa60933c86269947)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/64143/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 047f4513c1f1c48e74b1711b64f371f63ac11036)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/64147/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 3618e96adf30fa7c7a0a2b43cb582293e5d6784f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/64148/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into e7e35ab7823cc5b9c0904dfd1bf9a36c4060d287)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/64149/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 4f07eee65c46f7024d82b3831175e379d31f3ec2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/65791/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 885ea099036a73a0d6c3db3b431d0cf9690e9e24)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/66018/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec04cb4c1933901ee4c4b71206df3c48fb637ead into 98dbca2b04d0597995e96ef9ff067d2244d4cd13)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/66044/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3287311e395b585a2973c7e9a4c01f558f5e85bd into 98dbca2b04d0597995e96ef9ff067d2244d4cd13)

**Pull request merged**
