### PR TITLE
Send last_seen_at column when syncing systems

### PR DESCRIPTION
**Pull request by mssola**
## Description

This will not happen if, for example, the only change is on the `last_seen_at` column an nothing else.

This change is related to report more consistent data to SCC.

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by mssola** [comment]
[[URAS] Up-to-date `last_seen_at` attribute from systems behind regproxies](https://trello.com/c/6yyErGAk/2262-uras-up-to-date-lastseenat-attribute-from-systems-behind-regproxies)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/233888/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged af18ca719f0caef376b142e0b9b00c3aea482009 into 9dd978122d9b41675b3cff2943beaed4b7c142f6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/234257/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 0487b2ca941ae1ca5c6e61159061dbe197451e73 into 6dafe9ce136fc98ec570ce420bed82c775bc2fff)

**Review by ngetahun — APPROVED** [review]
LGTM! Tested by first registering then activating an extension. Both times, `last_seen_at` was updated.

**Pull request merged**
