### PR TITLE
Fix spec file, removing /usr/share/public/ symlinks

### PR DESCRIPTION
**Pull request by felixsch**
## Description

rmt 2.6.11 introduced a bug in our spec file removing symlinks from `/usr/share/rmt`. Namely `/usr/share/rmt/public/repo` and `/usr/share/rmt/public/suma` are removed, breaking existing RMT installations.

Please describe your change and provide as much context as possible.

Readding the symlinks to the files section in the spec file and marking them as `%ghost` (making rpm aware this file is dynamically created but still owned by the package), fixes the issue.

Fixes # (issue)

- https://bugzilla.suse.com/show_bug.cgi?id=1188043

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

I want to bump version here even if this is a minor change. But all 2.6.11 installations can upgrade with this fix easily and do not run into problems (helps all users using openSUSE:Factory).

How to review this:

- Build the package by coping dist files to your osc package directory
```
# in rmt repo in branch
make dist
cp -r package/obs/* <osc-package>
# in osc package directory
rm rmt-server-2.6.11.tar.gz
osc addremove
osc build SLE_15
osc build SLE_15_SP3
```

- Test installation and upgrade paths

### Testing installation and upgrade paths
requires: container images from the connect repository

1) Upgrade from an older version to 2.6.12

```
# docker run --privileged --rm -ti connect.15sp0 /bin/bash
> SUSEConnect -r <dev-regcode>
> zypper in rmt-server
> zypper show rmt-server | grep Version
# Should show not 2.6.11
> ls -la /usr/share/rmt/public
# symlinks exist
> zypper ar https://download.opensuse.org/repositories/home:/fschnizlein:/branches:/systemsmanagement:/SCC:/RMT/SLE_15/home:fschnizlein:branches:systemsmanagement:SCC:RMT.repo
> zypper in rmt-server-2.6.12-x86_64
> ls -la /usr/share/rmt/public
# symlinks still exist

```

2) Install new 2.6.12

```
# docker run --privileged --rm -ti connect.15sp3 /bin/bash
> SUSEConnect -r <dev-regcode>
> zypper ar https://download.opensuse.org/repositories/home:/fschnizlein:/branches:/systemsmanagement:/SCC:/RMT/SLE_15_SP3/home:fschnizlein:branches:systemsmanagement:SCC:RMT.repo
> zypper in rmt-server # make sure its coming from the dev branch
> zypper show rmt-server | grep Version
# Should show 2.6.12
> ls -la /usr/share/rmt/public
# symlinks exist
```

3) Upgrade from broken 2.6.11 to 2.6.12 and check if directories reappear

```
# docker run --privileged --rm -ti connect.15sp3 /bin/bash
> SUSEConnect -r <dev-regcode>
> zypper in rmt-server
> ls -la /usr/share/rmt/public
# symlinks exist
> zypper ar https://download.opensuse.org/repositories/systemsmanagement:/SCC:/RMT/SLE_15_SP3/systemsmanagement:SCC:RMT.repo
> zypper up --allow-vendor-change rmt-server
> zypper show rmt-server | grep Version
# Should show 2.6.11
> ls -la /usr/share/rmt/public
# symlinks are gone
> zypper ar https://download.opensuse.org/repositories/home:/fschnizlein:/branches:/systemsmanagement:/SCC:/RMT/SLE_15_SP3/home:fschnizlein:branches:systemsmanagement:SCC:RMT.repo
> zypper up --allow-vendor-change rmt-server
> ls -la /usr/share/rmt/public
# symlinks are back again
```

4) Changed symlinks in `/usr/share/rmt/public`

```
# docker run --privileged --rm -ti connect.15sp3 /bin/bash
> SUSEConnect -r <dev-regcode>
> zypper in rmt-server
> ls -la /usr/share/rmt/public
# symlinks exist
> unlink /usr/share/rmt/public/repo
> unlink /usr/share/rmt/public/suma
> ln -s /tmp /usr/share/rmt/public/repo
> ln -s /tmp /usr/share/rmt/public/suma
> ls -la /usr/share/rmt/public
# symlinks are changed
> zypper ar https://download.opensuse.org/repositories/home:/fschnizlein:/branches:/systemsmanagement:/SCC:/RMT/SLE_15_SP3/home:fschnizlein:branches:systemsmanagement:SCC:RMT.repo
> zypper in rmt-server-2.16.12-x86_64
> ls -la /usr/share/rmt/public
# symlinks are still changed
```

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/208867/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2a6871a360c893bcf06d688efcc02c8a4fdae9d6 into 4cdfac6d7a035ddeb66450d7216c8d0b01e4ead8)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/208950/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2a6871a360c893bcf06d688efcc02c8a4fdae9d6 into 267e94f6193bc26d9b9188bbec2420d13406594c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/209081/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4e2433df2cde368db4d728238725b243f7dbddb3 into 267e94f6193bc26d9b9188bbec2420d13406594c)

**Pull request merged**
