### PR TITLE
Fix duplicate location in nginx config

### LINKED ISSUE #412: Conflict in nginx config: /rmt.crt
https://github.com/SUSE/rmt/blob/master/package/files/nginx/nginx-http.conf#L46

conflicts with

https://github.com/SUSE/rmt/blob/master/package/files/nginx/nginx-http.conf#L50

because it defines the same location (`/rmt.crt`) as

https://github.com/SUSE/rmt/blob/master/package/files/nginx/http-certs.conf#L3

### PR DESCRIPTION
**Pull request by ikapelyukhin**
Fixes #412.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/4036/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c48210cc6809e027da09563c12c6edfa52fabedf into 80598413be938f78d8a2b856f0c91f21071ea867)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/4038/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c48210cc6809e027da09563c12c6edfa52fabedf into 80598413be938f78d8a2b856f0c91f21071ea867)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/4040/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c48210cc6809e027da09563c12c6edfa52fabedf into 80598413be938f78d8a2b856f0c91f21071ea867)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/4295/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged c48210cc6809e027da09563c12c6edfa52fabedf into 6b11ef0359bd82ca1336963491924e9750c99ea8)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/4296/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8b435005fda02f31e9878c215104e247e44895d3 into 6b11ef0359bd82ca1336963491924e9750c99ea8)

**Comment by ikapelyukhin** [comment]
@wstephenson merged.

**Pull request merged**
