### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

Because we've enabled the installer updates repository, we have more repositories in our list than before. If we don't remove them from the list with grep, the list will grow with every newly released product and break our tests.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by tmuntaner** [comment]
Whether or not we need to merge this depends on the outcome of #607. If we change the behavior of installer repos being enabled by default, maybe we don't need to filter the list anymore.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/129737/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c1c1e894b2e456a9d0467bf61d48fb25cce30d7b into f34602cb37c2b137cc71df1d58c92af6db2cc21e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/129738/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b36b57fc24bf5e360daf0bcdabbbd53c1d6c6b39 into f34602cb37c2b137cc71df1d58c92af6db2cc21e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/129933/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b36b57fc24bf5e360daf0bcdabbbd53c1d6c6b39 into 0be02d2aec3c3559122bf11232827c8136112bd7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/129934/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b36b57fc24bf5e360daf0bcdabbbd53c1d6c6b39 into 686c10104543846e390205b917b532fdecff2833)

**Comment by tmuntaner** [comment]
@lcaparroz thanks, but before I consider merging this, I will wait and see if the other issue is fixed.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/130259/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b36b57fc24bf5e360daf0bcdabbbd53c1d6c6b39 into 0a649e2e4df8b32d99803dc78af3e32fdd07bd0e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131040/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b36b57fc24bf5e360daf0bcdabbbd53c1d6c6b39 into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131573/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 90fa2751c82473efe40f41cc086471e2666f01df into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

**Pull request merged**
