### PR TITLE
Handle SCC connected BYOS instances

### PR DESCRIPTION
**Pull request by jesusbv**
- Track BYOS instances in the database
- Validate BYOS through SCC from RMT

## Description

When handling BYOS, it would be a good idea to track those in the database
as well as validate the instances through SCC

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [X] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [X] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Happy to update changelog if decided so

### CODE REVIEW

**Comment by digitaltom** [comment]
@jesusbv could you add the engine testsuites to the github actions CI (https://github.com/SUSE/rmt/blob/master/.github/workflows/integrations.yml)? 
By that you can have more confidence not to merge anything to master which fails.

**Comment by jesusbv** [comment]
> @jesusbv could you add the engine testsuites to the github actions CI (https://github.com/SUSE/rmt/blob/master/.github/workflows/integrations.yml)? By that you can have more confidence not to merge anything to master which fails.

Yes, that is a good idea, I have been working towards that goal, with a PR updating the engines tests
Will add those tests to the GH actions CI in a different PR

**Comment by digitaltom** [comment]
Could you please add a workflow how to test this feature?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/218456/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e41f785368c04b9050a355596a1ea4c5ee7711ea into 0cf4eb19f05bcaaf010782b296e1e588a02eb559)

**Pull request closed without merging**
