### PR TITLE
Update OBS repos mentioned in readme

### PR DESCRIPTION
**Pull request by wstephenson**

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/14697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a4bf0f133b044e89cecc636a66b18f3bab2beba6 into f06fa3c8d156af25e5bac0eb8afd66ef719d8921)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/15330/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged a4bf0f133b044e89cecc636a66b18f3bab2beba6 into 0f0459635cd7756df430ae881b79a8bdabe96a29)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16422/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a4bf0f133b044e89cecc636a66b18f3bab2beba6 into f4541f3c3ebd0748cbc9855eeb809e1b7efc84b1)

**Pull request merged**
