### PR TITLE
Fix ruby3 factory builds

### PR DESCRIPTION
**Pull request by ngetahun**
## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Review by digitaltom — APPROVED** [review]
LGTM as a fix for the build. Do we know if RMT actually works with Ruby3?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/235172/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f9524e16a9e937feede3323d52c5f062bb0ea3d5 into 216541c025bf2eb2435f6cc2683f7fb55da94937)

**Review by jesusbv — APPROVED** [review]
LGTM

**Comment by jesusbv** [comment]
> LGTM as a fix for the build. Do we know if RMT actually works with Ruby3?

I got the bug assigned to me and I haven't tried it with Ruby3
Was taking a look the other day to fix the build, so thanks Natnael

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/235349/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f9524e16a9e937feede3323d52c5f062bb0ea3d5 into 3ca892d00041ada0c984af7e1b12950c1a910f2a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/235485/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged cf12a376cc5afac41ac12e4b5771bacb56b0d358 into 3ca892d00041ada0c984af7e1b12950c1a910f2a)

**Pull request merged**
