### PR TITLE
Update strings marked for translation

### PR DESCRIPTION
**Pull request by lcaparroz**
## Description

After an internal proofreading round, some strings needed to be updated to improve the text.

## Change Type

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [X] **Documentation Update** (a change which only updates documentation)

## Checklist

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [X] I have provided comments for any hard-to-understand code.
- [X] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [X] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/336300/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged f4ceb9cf9530424411bfb43af972ac750f93ab9f into 293eb57a277f7d5ec6362a6837cffbe81b96566e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/336442/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f4ceb9cf9530424411bfb43af972ac750f93ab9f into 3a6737a2da0ddc932a99b008b6aa82b8885ff037)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/336443/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8a71f604adc1b5df87c4e8750178990cc4a95cfa into 3a6737a2da0ddc932a99b008b6aa82b8885ff037)

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

**How I reviewed this pull request:**

- Checked that the changes match the ones provided by Padraig (translation team)

**As always, if you think I missed something please let me know!** :rocket:

**Pull request merged**
