### PR TITLE
Refactor RMT Mirror Downloader

### PR DESCRIPTION
**Pull request by lcaparroz**
## Description

I refactored the classes `RMT::Mirror` and `RMT::Downloader` to improve how they communicate with each other, focusing on making `RMT::Downloader` to only accept instances of `RMT::Mirror::FileReference`.

### Detailed Description

The RMT::Downloader had a public interface which was quite complex:

* A new instance was initialized with parameters that could be modified later by an external agent: repository URL, and repository and cache directories. `RMT::Mirror` creates a `RMT::Downloader` instance during initialization and then modifies these attributes whenever it wants to download a different set of files, so it was hard to know, at any given point, what was the downloader configuration/state. These parameters were used solely for building URLs and paths for the downloaded files.
* RMT::Downloder public methods `#download/#download_multi` could receive `String`, `RepomdParser::Reference` and `RMT::Mirror::FileReference` instances, deciding how to create a request based on the object's class.  The method #download also accepted  the file checksum as an optional parameter, but the reference objects already hold this information. Both `String` and `RepomdParser::Reference` had just the relative path, used to build the URL.

I refactored `RMT::Mirror` and `RMT::Downloader` in an attempt to eliminate this complexity:

* `RMT::Mirror::FileReference` now has attributes for the file's cache path and remote path (URL), eliminating the need to initialize `RMT::Downloader` with them.
* `RMT::Downloader` should only receive `RMT::Mirror::FileReference` instances instead of accepting `String`. Also, it no longer has the responsibility for building file and URL paths.

Also, `RMT::Mirror` contained several methods relied directly on instance variables, by accessing them with `@var_name` references. Furthermore, these variables were set in one block of the code and used
in another, not making entirely clear where the values were needed.

I rewrote some methods to receive the values as arguments instead of accessing the instance variables, and for values which are set during initialization, I create private attribute readers, so `@var_name` is
only used during `RMT::Mirror.new`.

## Change Type

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)
- [x] Code refactoring

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/137623/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4b6d2ee7bf4485552dd46fa564dbfa7d846bc6c6 into f010687a6f9ec117811e3ed892cd509339b0a705)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/138418/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4b6d2ee7bf4485552dd46fa564dbfa7d846bc6c6 into 8bf6dc45c70f0efce10044563fd7e2bdd6378c51)

**Review by tmuntaner — CHANGES_REQUESTED** [review]
Looks good so far, but a few small comments.

**Review by tmuntaner — APPROVED** [review]
looks good to me

**Pull request merged**
