### PR TITLE
Changelog for pr #556

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

Please describe your change and provide as much context as possible.

## Change Type

*Please select the correct option.*

- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by tmuntaner** [comment]
This PR completes #556 with a changelog and MANUAL.md entries.

**Comment by tmuntaner** [comment]
This PR fixes #624.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/132841/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged b57d0deea19bf499d59f87208b0d53e723d2dc15 into bea2a88b046943eff8f7bf90b352585c61847eaf)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132972/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b57d0deea19bf499d59f87208b0d53e723d2dc15 into bea2a88b046943eff8f7bf90b352585c61847eaf)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132976/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 98898c7a54903bd728cfb592e05fac3737aff745 into bea2a88b046943eff8f7bf90b352585c61847eaf)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132980/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 98898c7a54903bd728cfb592e05fac3737aff745 into a42943aaa5aab41df37ae3c399065a5438898d0c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132981/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 98898c7a54903bd728cfb592e05fac3737aff745 into 6fc1d330974b42765d6ee037f7d59ae28b824d85)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132982/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f52de72bf823ff68722ddc56dd4611b9cbb85b16 into 8a421d990f8b50d9582c16e2eda156eb576d4279)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/133153/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f52de72bf823ff68722ddc56dd4611b9cbb85b16 into 009e6c36528eab860ec50a254724121ac9bf0236)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/133157/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1c9230bb3c2e71a7d4e8c82695268d294df6e787 into 6a75c0d7a7454f589213dce5c3717eea452847a4)

**Review by lcaparroz — APPROVED** [review]
LGTM :+1:

**Pull request merged**
