### PR TITLE
Add release_stage attribute to ProductSerializer

### PR DESCRIPTION
**Pull request by felixsch**
## Description
**See:** https://bugzilla.suse.com/show_bug.cgi?id=1176628
**Part of:** https://trello.com/c/Q5zEBJvj/1996-project-maintenance-connect-rmt-yast-rmt

Add `release_stage` to `V3::ProductSerializer` to allow `yast` and other programs correctly identify released products.

## How to test
- Run this branch on your local machine
- Call any products endpoint and check `release_stage` is included in the `json` response. (https://scc.suse.com/connect/v4/documentation)

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/200851/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e90ca6f87e5ace275b4b03479df9fb84aa412284 into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202269/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e3e8b2f798c457cd59e0435d1b2bc8647ad634b7 into 9228f9da8667575db38b9cab33b6596cf035a340)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202284/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e3e8b2f798c457cd59e0435d1b2bc8647ad634b7 into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202733/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f854c5732944c7d53cbcc05efb034d0e9daba2d2 into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
