### PR TITLE
Move Danger checks to CI steps

### PR DESCRIPTION
**Pull request by ngetahun**
## Description

As part of our move to GitHub Actions, our danger checks were failing to run on PRs from forks. To mitigate this, we removed Danger and replaced it with a script.

Card: https://trello.com/c/wDHTutUz/2034-rmt-move-danger-checks-to-ci-step-execution
## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by ngetahun** [comment]
[[RMT] Move Danger checks to ci step execution](https://trello.com/c/wDHTutUz/2034-rmt-move-danger-checks-to-ci-step-execution)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger-pr">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204460/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 64d142c08eabc02af6c4082dc76208c2d342220a into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204461/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9fb1ca436ccaeb4df80ff67796af3ecf28175a4d into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204462/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ffd9df7751faad4e5e87ef20427dd383de905541 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204466/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5b122b47e7673a378a58739c72c2407565151df3 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204477/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged cde1af7becc36380a2a14e14aa9b1585a22a2b40 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/204478/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged d67b0bdd9af4e30294a47e65379dd98a6a1cb3c8 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204948/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d67b0bdd9af4e30294a47e65379dd98a6a1cb3c8 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204949/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7a02205fc6d68f76e0a642f8a62d24137866b053 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204950/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 414a338b34b2d30576e34be1f488974fbc016181 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204951/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 6da16ed2b92ac24e6f2e84515600e6fe01af765f into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204953/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 23476e15d6dfa0fae8247f5894184a18b24d3eaa into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204964/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b347a02e242a490c1c5db3a20c4e9b1f4b3e13fb into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204967/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged bd8320c296dc082865722e77d26fef977bd5d4df into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204968/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3413111b676e97f41374fbf939cdc734bd21ec00 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204969/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 12971904c75cc50bb2b20039a4e24d53779f2885 into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204973/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7b544e85306c283138a34152e48a00bb7967bbdf into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/204974/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3d06b2dc81abfd441f33569420de13f29bf3c45f into 17004b32ac3f41f209405488777027cdef4e3163)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/205084/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 874a62d4b4dedeed4d8e513456a4ddc57be5af0e into 17004b32ac3f41f209405488777027cdef4e3163)

**Review by digitaltom — APPROVED** [review]
As discussed with @ngetahun, this is a temporary fix to get CI working with prs from forks. 
Visibility of the `danger` warning regarding changelog entries is mostly lost because it's hidden pretty deep in the gh actions output.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/205300/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 874a62d4b4dedeed4d8e513456a4ddc57be5af0e into 3b37b497194bb510a371c7ac507bb121287c1b92)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/205402/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 113c215c77403287ccee7fb191a3c90f8d53548b into 3b37b497194bb510a371c7ac507bb121287c1b92)

**Pull request merged**
