### PR TITLE
Update RMT/SMT and SUMA comparison cheet

### PR DESCRIPTION
**Pull request by felixsch**
## Description
Adding SUMA to the proxy comparison chart. This was originally done here: https://github.com/SUSE/rmt/pull/718 but the pull request went stale. To not lose the effort added the suggested changes and updated the pull request.

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/201799/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7a0d3b62979ed989ac6ee2ba01aaf83123123bd3 into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger-pr">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202269/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7a0d3b62979ed989ac6ee2ba01aaf83123123bd3 into 9228f9da8667575db38b9cab33b6596cf035a340)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202270/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 763fe414a471c286c2d720840cbefaff28b3d4a0 into 9228f9da8667575db38b9cab33b6596cf035a340)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202284/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 763fe414a471c286c2d720840cbefaff28b3d4a0 into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202733/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 865636fb0e129f4f60598acba434bbd8656569bd into 3aaec0e8c7e729f4ae431bccb0af6de7f9235ef9)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202764/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3913b2870e3541a17eb2d25c0dcd8f4c847bea46 into 7d8d070c942fd90d6e39d55a0a4600d472ec9f59)

**Pull request merged**
