### PR TITLE
Show repo's friendly id on error log messages when mirroring

### PR DESCRIPTION
**Pull request by josegomezr**
## Description

RMT reference host is erroring on a repository mirror, but the message contains a confusing id.

```
Jan 07 03:52:04 rmt rmt-cli[23511]: WARN: The following errors occurred while mirroring:
Jan 07 03:52:04 rmt rmt-cli[23511]: WARN: Repository 'SLE-Product-SLES_SAP15-Updates' (1659): Error while mirroring data: Failed to download 3 files.
Jan 07 03:52:04 rmt rmt-cli[23511]: WARN: Mirroring completed with errors.
```

@lcaparroz has confirmed is a problem with some packages in the repository (maybe outdated XML?) however the id printed (`1659`) is not useful to debug since is not aligned with #640. 

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Is using `friendly_id` in error messages appropiate?

### CODE REVIEW

**Comment by josegomezr** [comment]
I Intentionally left this untested to discover which tests needs changes 😅 I'll get back to this later

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164691/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 97cf7feb47062ae0cca90a7ebe3ae01a97e7393b into 9ca15bf4c6f6088efb8908145b0f54d3ab13079a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164719/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged 97cf7feb47062ae0cca90a7ebe3ae01a97e7393b into 30126a8db26f20e6059a1a1ba5dc7d30e4c5552e)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/164735/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 97cf7feb47062ae0cca90a7ebe3ae01a97e7393b into a955568196d04607499d2ca57a63285d628eb163)

**Review by gionaufal — DISMISSED** [review]

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/165821/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged f097e03918a7442dd3952752bebd62282e0141f0 into a955568196d04607499d2ca57a63285d628eb163)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/165825/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged ed423a99a29cc259fd92e8df85a3a3eecf026d52 into a955568196d04607499d2ca57a63285d628eb163)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/166957/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ed423a99a29cc259fd92e8df85a3a3eecf026d52 into 8a38a2bc5325bd64439770dc15e44343d67026eb)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/168040/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ed423a99a29cc259fd92e8df85a3a3eecf026d52 into db4e77ddac635da9c1d35b0464afbf81550fb257)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/170332/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into db4e77ddac635da9c1d35b0464afbf81550fb257)

**Review by lcaparroz — APPROVED** [review]

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/174671/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 4bebacb3abda3fbf1562f6cdaf606551d5568705)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/175712/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 920de39c1791930669c5dff8a5c9312c82b45750)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/176363/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/183914/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into bd51887f819592d95ee624b9baff5c1b9c88c898)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184060/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 2f3ec01812a78a6347efe45c183b1f6ab1d417ca)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184061/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 023f61747d6a2b527cbc0ac4f0a83d9845a423a3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184105/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 0aeb5c6fab7f7cde97e4fd59ff030b3fccfe59de)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184203/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184362/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 57c3e24d3da0e80b114e74bfb86842e218b2f7ff)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187263/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into c9a2c0a25899c58917d216fb150094001d39fb0b)

**Comment by digitaltom** [comment]
@josegomezr can this get merged?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187333/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1257a8361d49b98ca326db8d85a625f39e34a16f into 05412b52a3cbaf2f3886fe77f84685d3f71aee40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187334/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec03b1a7de41c18b46036afc4b95cdef9d966cea into 05412b52a3cbaf2f3886fe77f84685d3f71aee40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187335/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec03b1a7de41c18b46036afc4b95cdef9d966cea into 9502b3b8b05e8c8cdfc60a0407605bde36495a36)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec03b1a7de41c18b46036afc4b95cdef9d966cea into 263421b2813012775fb532fc8a8c4a59b1a6a68d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187453/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec03b1a7de41c18b46036afc4b95cdef9d966cea into e7110f4096c8c8d2543dad907879adb25fd98b76)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/188037/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec03b1a7de41c18b46036afc4b95cdef9d966cea into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/188385/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 658f889676cdac8210a677bde30832403a7d5612 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189560/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged db654d34349f7c4528b29c40d765de733084f343 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189565/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged db654d34349f7c4528b29c40d765de733084f343 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189683/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged db654d34349f7c4528b29c40d765de733084f343 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189696/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged db654d34349f7c4528b29c40d765de733084f343 into 771f28783396c9e4a5478bbf3825154110e96d86)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged db654d34349f7c4528b29c40d765de733084f343 into 4e784eb993d81d59161441fe6d3e4a26245e3f8b)

**Review by gionaufal — APPROVED** [review]
lgtm!

**Pull request merged**
