### PR TITLE
Add manual for setting log level

### PR DESCRIPTION
**Pull request by digitaltom**
## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [x] **Documentation Update** (a change which only updates documentation)

### CODE REVIEW

**Comment by digitaltom** [comment]
@ngetahun, @lcaparroz please see the requested update to the manual here.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/210415/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4d041c2e2cf64c2404217b303e379e68aa5b99c3 into 953bcb078e7a4b1ec6f2d8b26a1b9dd6655477c7)

**Comment by felixsch** [comment]
lgtm :+1: 

PS: Does it makes sense to set the `log_level` to `:debug` in the development configuration by default?

**Comment by digitaltom** [comment]
@felixsch I think I wouldn't set it to debug for the CLI by default, it's pretty noisy. For the rails log it's a good idea.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/211249/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged aef9433258bfee890d883f1e790100f9e7b1a498 into 953bcb078e7a4b1ec6f2d8b26a1b9dd6655477c7)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/211389/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged aef9433258bfee890d883f1e790100f9e7b1a498 into eedb891d469aacb56677ae289800a94cc979e512)

**Pull request merged**
