### PR TITLE
Run integration tests on SLE 15.3

### PR DESCRIPTION
**Pull request by Sergeykot**
## Description

Run integration tests on SLES 15.3

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229404/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged b4b98354b9c1d6579008fe9ac3f4106cc6c5916f into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229408/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged b4b98354b9c1d6579008fe9ac3f4106cc6c5916f into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/229411/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged b4b98354b9c1d6579008fe9ac3f4106cc6c5916f into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/229412/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged aee766580458bd14bc1fa991de69f8cde163a6ed into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/229668/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged aee766580458bd14bc1fa991de69f8cde163a6ed into 985ca90384875e9a19b2ec79d5529f3741da4e07)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/230312/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged aee766580458bd14bc1fa991de69f8cde163a6ed into dea8b243bba218abb1aeaee61314bc495306cc7a)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
