### PR TITLE
github: added the stale bot

### PR DESCRIPTION
**Pull request by mssola**
## Description

Added the stale bot, which will allow us to have more awareness on pull requests which are stuck in the development process.

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

### CODE REVIEW

**Comment by mssola** [comment]
[Experiment: add `stale` bot into our projects.](https://trello.com/c/Pzq6bqs0/2318-experiment-add-stale-bot-into-our-projects)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240537/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 56dc87b3ab44d515195028add15f4f93cbde89a6 into 8c4553d761653f359c40c0802e8467e8b414596d)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240560/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 56dc87b3ab44d515195028add15f4f93cbde89a6 into c1a3c5b7b2eae5343d70f029e1154331ed447e6e)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240642/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f6db08445fef6acf1a05e0b5ea95f4382c7893c1 into c1a3c5b7b2eae5343d70f029e1154331ed447e6e)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240651/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f6db08445fef6acf1a05e0b5ea95f4382c7893c1 into 9a138413e0dfee3008a477858111cd804752ef25)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240655/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f6db08445fef6acf1a05e0b5ea95f4382c7893c1 into 676099d07631ecff2814aaddc0d75765687f3224)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240656/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f6db08445fef6acf1a05e0b5ea95f4382c7893c1 into 62e174c483011213c57514b5fc5603ee0f2d1bc2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240828/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f6db08445fef6acf1a05e0b5ea95f4382c7893c1 into 2822b51bb0d857e45d8570b58181295a088967fc)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240943/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 0b40390998fcf17c20648be7c9dfe97b657fb2a4 into 2822b51bb0d857e45d8570b58181295a088967fc)

**Pull request merged**
