### PR TITLE
Update `scc-codestyle` to the latest version, regenerate rubocop todo

### PR DESCRIPTION
**Pull request by arharovets**
## Description

The latest changes to `scc-codestyle` gem brought a lot of new rules and, most importantly, moved some of the existing ones to another sections, so an existing Rubocop TODO file is incompatible with `scc-codestyle` Rubocop configuration.
This upgrades `scc-codestyle` to version `0.5.0` and regenerates a Rubocop TODO file.

Further details: [scc-codestyle PR](https://github.com/SUSE/scc-codestyle/pull/99)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/216887/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ec93828c49c4e725ac45c9401c72d2d1de8ed7af into 5ab5fab22a2832c113e6f49506b3f85886cd2b15)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/218058/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged bd7b155c47f2e24d02dde547710cf178425ace74 into 24867767449eb81d94570e1248628a7f0f1b68b1)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/218059/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images. (Merged 1ecae52a53e9c66eba8b4c7c078f20feeaba8f99 into 24867767449eb81d94570e1248628a7f0f1b68b1)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/218240/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged 3c5c2dd4c84d6b57f77516c3a49fce7c0a5b0cf4 into 050e9f803a04cecdaa53949798144e04d0bb6207)

**Pull request merged**
