### PR TITLE
Ipv6

### LINKED ISSUE #838: nginx does not respond on IPv6 as configured
The provided configuration files do not enable nginx (as tested on SLES 15 SP3) to respond to requests via IPv6, only IPv4.

### PR DESCRIPTION
**Pull request by bear454**
## Description

Enable nginx configurations to serve RMT on IPv4 & IPv6.

Fixes #838 

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by bear454** [comment]
[IPv6 support](https://trello.com/c/FkKunWJy/2256-ipv6-support)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231673/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3de68d6d63d1a55365c99b6acac808239319c4b0 into 62e114830c657a2bbfb31937658f417267316861)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/231898/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 3de68d6d63d1a55365c99b6acac808239319c4b0 into d487fbb1c8558fcc13e137be8793d041c02ee199)

**Review by ngetahun — APPROVED** [review]
LGTM.

Tested by starting docker compose: `docker-compose up --build -d`
And did a ipv6 curl: `curl -I6 localhost:8080`

**Comment by ngetahun** [comment]
@bear454 Please update the PR

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/233946/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b07b5d21fd5bc9aca931ab685a1e6e7aeecdcfa into 9dd978122d9b41675b3cff2943beaed4b7c142f6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/234256/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b07b5d21fd5bc9aca931ab685a1e6e7aeecdcfa into 6dafe9ce136fc98ec570ce420bed82c775bc2fff)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/234910/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9b07b5d21fd5bc9aca931ab685a1e6e7aeecdcfa into 216541c025bf2eb2435f6cc2683f7fb55da94937)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/235349/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 9b07b5d21fd5bc9aca931ab685a1e6e7aeecdcfa into 3ca892d00041ada0c984af7e1b12950c1a910f2a)

**Comment by ngetahun** [comment]
@bear454 Please fix the merge conflicts.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237158/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 517cde7e664fc642944560ce111e32ad55d897ea into 5ea30405fee70f1ea5de0282bff6130675603185)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237294/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 517cde7e664fc642944560ce111e32ad55d897ea into 374238e9fae4cd8f41f4423341b82b6f8477c17c)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237295/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 517cde7e664fc642944560ce111e32ad55d897ea into e528cd35b04790d621bebd258ec090648dc10052)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237429/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 9b86cde2e5270087194712ad63db8622940a9fd8 into e528cd35b04790d621bebd258ec090648dc10052)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237439/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 9b86cde2e5270087194712ad63db8622940a9fd8 into e528cd35b04790d621bebd258ec090648dc10052)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237602/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 9b86cde2e5270087194712ad63db8622940a9fd8 into e528cd35b04790d621bebd258ec090648dc10052)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/237607/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 63e10bd3b64cc0eba5b06bb70fea6f0055731443 into e528cd35b04790d621bebd258ec090648dc10052)

**Pull request merged**
