### PR TITLE
PubCloud: allow access to SLES 12 SP1 repos when SLES 11 was activated

### PR DESCRIPTION
**Pull request by ikapelyukhin**
Allows access to repos that were not yet activated in order to allow for SLES11 systems to be migrated.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/49687/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f0ac4f5d65291f6fddf69af67b6014c3eeecf2a3 into 8223a4beb0d62ed620f2cd4543e26a63a41c5cf8)

**Comment by digitaltom** [comment]
Could you explain in which workflow this is needed? 
RMT should already support (offline-) system migration from 11 to 12.

**Comment by rjschwei** [comment]
There is n "offline" migration from 11 to 12 in the Public Cloud. We have an ugly process [1] that allows users to move to 12 for their running instances. This involves getting the SLES 12 SP1 repos onto their system via tarball.

While the blog is old we received to incidents since we switched to RMT about failed upgrades. The idea is to enable the upgrade path until we enable strict access control during repo access, at which point the new code path will no longer work either. This will be publicized via another blog and addition to the existing blog.

[1] https://www.suse.com/c/upgrading-running-demand-instances-public-cloud/

**Comment by ikapelyukhin** [comment]
@digitaltom we use `strict_authentication` plugin, which prevents access to the repos unless a product is activated on the system. Obviously SLES12 repos aren't activated on SLES11 systems (and there's no way to activate them, because there's no SUSEConnect).

Those changes are affecting just `rmt-server-pubcloud` package, though.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/49962/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 370d68b5facc67f2119c63e71869e1a1839cd8fd into ed117304ce57fa70fa8a2ff39d1fdb46a2d2033e)

**Pull request merged**
