### PR TITLE
Final translation round

### PR DESCRIPTION
**Pull request by likhitha77**
## Description

Last step in translations round. Enabling translations for the marked strings

#### How to test
* Set the language using the LANG variable while calling rmt-cli. Example: `LANG=de rmt-cli products ls`
* Ensure that the response is translated

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by likhitha77** [comment]
[Translation Round - Finishing Touches](https://trello.com/c/IBFejE9C/3073-translation-round-finishing-touches)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/345592/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 2cb2f1723cac32b1d795949435cb9810d748f4a9 into b633992331ac8df06f941341b540ec31a4a59afd)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/345769/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 417202dce00cf4b8b66f8917d6db6c312efe0321 into b633992331ac8df06f941341b540ec31a4a59afd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/345966/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 417202dce00cf4b8b66f8917d6db6c312efe0321 into 017d3bee69a44b38eb5474f7ba923916f83ceb9c)

**Pull request merged**
