### PR TITLE
Fix migration for downloaded_files.local_path

### PR DESCRIPTION
**Pull request by lcaparroz**
The migration for adding index/uniqueness to `downloaded_files.local_path` didn't performed well on a test within a database with 300k+ records:

* The `DELETE` statement would lock the DB for a considerable amount of time, which caused a lock wait timeout error (both using ActiveRecord or MariaDB console);
* Even converting the statement to a `SELECT` didn't work, as the query would get stuck "forever".

Since the ecosystem of RMT customers may considerable vary, we rewrote the migration to improve the query execution time and to delete one record a time, avoiding locking the DB for so long.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by ikapelyukhin** [comment]
Is it actually faster after the change? Might be server side cache or all the duplicates actually got dropped in the timed out request.

It is slow because there's no index on `local_path`, maybe an non-unique index needs to be created on it first, then duplicates removed (this time faster because looking through the whole table wouldn't be required) and then re-create the index as unique.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/127425/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 9923e93bbe845046fcbf4ceb682d79a0e6b7aa2d into 9c849995f4c3770d6406ae85abcfc8fdbc2729d4)

**Comment by lcaparroz** [comment]
> Is it actually faster after the change? Might be server side cache or all the duplicates actually got dropped in the timed out request.
>
> It is slow because there's no index on `local_path`, maybe an non-unique index needs to be created on it first, then duplicates removed (this time faster because looking through the whole table wouldn't be required) and then re-create the index as unique.

I tested this query on our RMT host, which contains at least 300k records (and no duplicates), it takes about 70~80 seconds to execute. Then, I converted the previous version to do only a `SELECT` and let it run for at least 3 minutes before stopping it manually; it did not finish.

Our major problem is deleting in one single SQL statement, the database is being locked for a considerable amount of time, so we decided to separately delete each record. If indexing the field and then deleting takes less than 80 seconds, it would be worth a try.

If I got it correctly, your suggestion would have the following steps:

1. Add index to `local_path`, **without** uniqueness;
1. Delete all duplicated records;
1. Remove index from `local_path`;
1. Add index to `local_path`, **with** uniqueness.

And the current solution is:

1. Delete all duplicated records;
1. Add index to `local_path`, **with** uniqueness.

I'd need to prepare some environment to test your suggestion, creating some duplicates to check how it  would perform. Ideally, RMT would not create duplicates by itself, so if a system has any, it should be a few records.

**Comment by ikapelyukhin** [comment]
> If I got it correctly, your suggestion would have the following steps:
> 
>     1. Add index to `local_path`, **without** uniqueness;
> 
>     2. Delete all duplicated records;
> 
>     3. Remove index from `local_path`;
> 
>     4. Add index to `local_path`, **with** uniqueness.

Yes.

> I'd need to prepare some environment to test your suggestion, creating some duplicates to check how it would perform. Ideally, RMT would not create duplicates by itself, so if a system has any, it should be a few records.

See how long it takes to create a non-unique index on 300k records, it shouldn't matter if there aren't any duplicates there. If creating the index takes too long -- then maybe it's not such a good idea to re-create it again.

**Comment by josegomezr** [comment]
If the table has 100k dupl records, that'd mean 100k delete queries. Wouldn't it be faster & easier to:

1. first fetch only the list of ids of duplicated files
2. delete in batches of 1k/2k/5k (a single `delete from downloaded_files where id IN (batch_list)` per batch)
3. make the index.

:question:

**Comment by ikapelyukhin** [comment]
> first fetch only the list of ids of duplicated files

That's the most time consuming operation. There's no index on `local_path`, so it has to look through the whole table to find the duplicates.

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/128014/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a048a67316ac8c40434ad5df5c723ce414d0f8d2 into 9c849995f4c3770d6406ae85abcfc8fdbc2729d4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/128156/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a048a67316ac8c40434ad5df5c723ce414d0f8d2 into 9c849995f4c3770d6406ae85abcfc8fdbc2729d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/128203/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged a048a67316ac8c40434ad5df5c723ce414d0f8d2 into 76a5d95df80154dce699c815ad992ffb4d576338)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/128205/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a048a67316ac8c40434ad5df5c723ce414d0f8d2 into 297e681e15fac71c2c56886f78d696595e00d009)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/129168/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1f3f30acbb3bee169736181ff5689395ab681bf4 into 892ab45071aad0523d98736422cdc383f80fa824)

**Review by josegomezr — APPROVED** [review]

**Pull request merged**
