### PR TITLE
Issues with custom repos and UTF8 collation

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

The old regex method of finding matches didn't work because of the way mysql collates utf8 content. Our regex would treat an "á" differently than an "a", however, mysql treats them as the same. This could cause an issue with duplicate entries with the same unique index. Instead, let's have mysql compare the strings for us.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x]  I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/141614/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 78c5f83b991bdcb1dcdba0201cb74d3ba729554f into 1a21b5ae151b70441f86e4c953b605a43651ef98)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/141633/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 04c1d37d2b2bf07a108eb2dedbe69e6eef049369 into 1a21b5ae151b70441f86e4c953b605a43651ef98)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/141646/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7bcbfb5cad79d3650ad478a17891c6cb877afcc9 into 1a21b5ae151b70441f86e4c953b605a43651ef98)

**Review by lcaparroz — APPROVED** [review]
LGTM :+1:

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/142454/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5f3b80aae6367ed39084f79c3281e5f641c62d45 into 210f7e62c946c409ee14bc7517cf8627014d1669)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/142482/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 82e0b2efca328192ed443af11abb220268119485 into 210f7e62c946c409ee14bc7517cf8627014d1669)

**Pull request merged**
