### PR TITLE
Accurate engines coverage

### PR DESCRIPTION
**Pull request by jesusbv**
## Description

Take into account for coverage engines code only

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [X] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [X] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/226317/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 0be5ca0888d8a4646bc2678dce66a64ff8339445)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/229668/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 985ca90384875e9a19b2ec79d5529f3741da4e07)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/230312/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into dea8b243bba218abb1aeaee61314bc495306cc7a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/230313/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 3f63bd1910985b7577633ab446fa50a810fcdf50)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/230448/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 3050b76d4cdbc26f60b3131a310b072bc3b38a7e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/230615/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 9492a7c54ad245e8232f0a49c26415e886e9bfbb)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231449/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 1b12c2a4302d462b116d8dcc33a87b6b30a216f1)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231673/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 62e114830c657a2bbfb31937658f417267316861)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231898/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into d487fbb1c8558fcc13e137be8793d041c02ee199)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231921/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 9dd978122d9b41675b3cff2943beaed4b7c142f6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/234256/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 6dafe9ce136fc98ec570ce420bed82c775bc2fff)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/234910/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 216541c025bf2eb2435f6cc2683f7fb55da94937)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/235349/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 3ca892d00041ada0c984af7e1b12950c1a910f2a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/235500/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 24bde1b3d7224a473e5db0d4c74102f72e526261 into 5ea30405fee70f1ea5de0282bff6130675603185)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237158/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 87c8e1a0677bf5a45f42585afd546df84c3a44e1 into 5ea30405fee70f1ea5de0282bff6130675603185)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/237294/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 87c8e1a0677bf5a45f42585afd546df84c3a44e1 into 374238e9fae4cd8f41f4423341b82b6f8477c17c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/237295/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 87c8e1a0677bf5a45f42585afd546df84c3a44e1 into e528cd35b04790d621bebd258ec090648dc10052)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/237622/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 87c8e1a0677bf5a45f42585afd546df84c3a44e1 into ffd67c966ecf0217ce87d6df27dc15d962f5b8f9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/238605/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 30cbbd46c28fa4f9fd353478cdd33c24b86e1c81)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240057/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 70a6550f2244474da8848ab49f0ca2e55dbe1bc4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240536/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 8c4553d761653f359c40c0802e8467e8b414596d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240560/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into c1a3c5b7b2eae5343d70f029e1154331ed447e6e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240651/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 9a138413e0dfee3008a477858111cd804752ef25)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240655/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 676099d07631ecff2814aaddc0d75765687f3224)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/240656/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 62e174c483011213c57514b5fc5603ee0f2d1bc2)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/240828/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 2822b51bb0d857e45d8570b58181295a088967fc)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/241752/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 8776d78d74db14b124a14650baeed30f44b00cca)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/241924/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into f365152aba8ffdcb8ebba4cf7f2d7137ab42d53b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/242070/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into cf82866246db34eebe5383a0107a3a7973db7101)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/242887/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into d1da0a4fbafe8d1b7835d52948dd49b5cbd10e69)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/242912/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 226eeb6a7f6496c9f862d709ed98a3d4030e415f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/243032/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 515ad1001ed55f6a137c70c2305aa51608d150a1)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/243221/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 5dbcee4396cca0d81ea891ab8fa35a9051e4a403)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/245190/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into b320b4baed5e7aafd25e295e08513c8d480af3cd)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/245506/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into c95985a223f3d51fb5373d888648abefae1b598b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249654/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 555a4b5ea3c4163ab58f0abb775fdb1dd7caeeea)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249678/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 30d9834cc7b5b22658035be97bea635419d65a2b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249679/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into a5b45e86206dd3d56651550ab561c96264b8dc0f)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/254530/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into ce2325855246f8d9bf64a374ef5597a8c5b41dc7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/254558/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into e1ba12c592c15f4f23401aaa1c9b31e62296cc2c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/259150/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into e99c2074d720fc3ee796cdb3ddac299344b41990)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/259508/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 10de13d346e473e72479a85542c90f2c1dec79b5 into 454855918e87bc5de7d526e497708e2e57e75488)

**Comment by digitaltom** [comment]
Obsoleted by https://github.com/SUSE/rmt/pull/907

**Pull request closed without merging**
