### PR TITLE
Update rmt-client-setup-res

### PR DESCRIPTION
**Pull request by zpetrova**
This fix make rmt-client-setup-res script work on CentOS. (bsc#1197038)

## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ x] I have reviewed my own code and believe that it's ready for an external review.
- [ x] I have provided comments for any hard-to-understand code.
- [ x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ x] RMT's test coverage remains at 100%.
- [ x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/248989/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a4b382eb0c1dfadf803c26b327d41be1c868621f into c95985a223f3d51fb5373d888648abefae1b598b)

**Comment by digitaltom** [comment]
I didn't run this on RES, but I guess you tested it? Looks good to merge. Should I add a changelog for the rpm?

**Comment by zpetrova** [comment]
Hi Tom, yes I've tested the script on latest CentOS, RES8.5 and RHEL8.0
Yes, please add a line to changelog.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249654/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a4b382eb0c1dfadf803c26b327d41be1c868621f into 555a4b5ea3c4163ab58f0abb775fdb1dd7caeeea)

**Review by digitaltom — APPROVED** [review]

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/249678/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a4b382eb0c1dfadf803c26b327d41be1c868621f into 30d9834cc7b5b22658035be97bea635419d65a2b)

**Pull request merged**
