### PR TITLE
factory_girl is no more, use factory_bot instead

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

The maintainers of factory_girl renamed the project to factory_bot.
Let's use factory_bot to get rid of our deprecation warnings.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/131254/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 76b4dd6138c5edb42c4a7f19d2572094c8bf4607 into 7f2bc38c466ce8dd5e4c611c0d54347457ecad45)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131574/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8488cc609aec81cd45e293e5b67a0df8a4bdeb33 into 8a2d4c3b42841bcb2d5a63a2b1cbf74d47f7acb0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/131738/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8488cc609aec81cd45e293e5b67a0df8a4bdeb33 into f68692072dc17f7a23a0ed00b94dea9a8f0beda0)

**Review by ngetahun — COMMENTED** [review]
LGTM! But there's a rubocop rule leftover from `FactoryGirl` [here](https://github.com/SUSE/rmt/blob/f68692072dc17f7a23a0ed00b94dea9a8f0beda0/.rubocop_todo.yml#L10)

**Comment by tmuntaner** [comment]
@ngetahun Updated

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/132822/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged b19b5bde86609a46f71de355b050c64549ac8747 into f68692072dc17f7a23a0ed00b94dea9a8f0beda0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/132831/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b19b5bde86609a46f71de355b050c64549ac8747 into f68692072dc17f7a23a0ed00b94dea9a8f0beda0)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by tmuntaner** [comment]
@ngetahun thanks

**Pull request merged**
