### PR TITLE
Update SMT/RMT comparison table

### PR DESCRIPTION
**Pull request by lagartoflojo**
## Description

Update the SMT / RMT comparison chart, specifying the supported versions of RES.

## Change Type

*Please select the correct option.*

- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/149697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 42495745c69991bc4e30d2f4d5407d126daf3c8f into 0c1a79d18b33f809011a251e4e0336bdb252db27)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/149698/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d46c9f4aa723ca4a4dc2a23075e838a12eb5aaa5 into 0c1a79d18b33f809011a251e4e0336bdb252db27)

**Comment by digitaltom** [comment]
Features we could mention that stand out in RMT compared to SMT: 

* Option to [run as container](https://github.com/SUSE/rmt/blob/master/README.md#development-setup---docker-compose)
* Easy development setup + [contribution guide](https://github.com/SUSE/rmt/blob/master/docs/CONTRIBUTING.md)
* [Availability](https://github.com/SUSE/rmt/blob/master/docs/installation.md#installation-on-opensuse-leap-15) on openSUSE Leap
* Bash completion 
* 100% test coverage
* [Plugin functionality](https://github.com/SUSE/rmt/blob/master/docs/PLUGINS.md) (used for public cloud extensions)

Available on both: 

* Cleanup functionality for not anymore used products

Is there also something RMT is providing with regard to SUMA? Because it does mirror the SUMA product tree file which SMT is probably not.

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by lagartoflojo** [comment]
> Option to run as container
> Availability on openSUSE Leap

This is not officially supported; do we want to put them in the comparison still?
I would not add them without a footnote to the effect of "Not officially supported by SUSE". Thoughts?

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/149893/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4c094b36541f2eb6850d36f467ad9e578eb9acbc into 0c1a79d18b33f809011a251e4e0336bdb252db27)

**Comment by digitaltom** [comment]
> > Option to run as container
> > Availability on openSUSE Leap
> 
> This is not officially supported; do we want to put them in the comparison still?
> I would not add them without a footnote to the effect of "Not officially supported by SUSE". Thoughts?

For Leap it's as supported as any other package on it, so I wouldn't make an extra note there. Regarding Docker, I think the self-support amendment is good.

**Review by digitaltom — APPROVED** [review]
Looks good for RMT now :-)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/149932/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 92ceb017fa7c775738cc46896b33cd32eda1e6e7 into 0c1a79d18b33f809011a251e4e0336bdb252db27)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/149933/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d2f4d62caa0f5af50a8218d8c0a5bbec7147d4b6 into 0c1a79d18b33f809011a251e4e0336bdb252db27)

**Pull request merged**
