### PR TITLE
Include Python2 module into SLE15 online migrations

### PR DESCRIPTION
**Pull request by Sergeykot**
Verification: 

`curl -u '<SYSTEM_LOGIN>:<SYSTEM_PASSWORD>' -H "Content-type: application/json" -d '{ "installed_products": [ { "identifier": "SLES", "version": "15", "arch": "x86_64" } ] }' -X POST <YOUR_SCC_HOST>/connect/systems/products/migrations`

### CODE REVIEW

**Comment by Sergeykot** [comment]
@digitaltom version updated

**Comment by digitaltom** [comment]
Don't we need to bump in the .spec file, too?

**Comment by Sergeykot** [comment]
yes, it is there https://github.com/SUSE/rmt/pull/370/files#diff-b3e1360c78d705d9a80e315442dbbbcbR32

**Comment by digitaltom** [comment]
Sorry, I overlooked that. Good to go!

**Pull request merged**
