### PR TITLE
Integrate proofread changes into our code base

### PR DESCRIPTION
**Pull request by felixsch**
## Description

Apply the changes from proofread session int our codebase.

card: https://trello.com/c/5s5msoEv/2680-translation-round-ask-for-translations

**How to test this PR:**

- Grab yourself the pot file for glue, from Padraigs email (RE: [1/3] Translation round for SCC and RMT: Proofreading)
- Checkout i18n branch (for the source pot file) and compare:

```
diff new/glue.pot locale/glue.pot
```
- Check that all changes are reflected in this PR

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

### CODE REVIEW

**Review by digitaltom — APPROVED** [review]

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/294108/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 45e4a02d1fd2985666ab38d17a8b8f98e93ab1d9 into f3dd1349677e600d9259cbe07953c39ad7af6773)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/294109/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d71d0dea3d1658721b0a44ceeea8f4f12dada133 into f3dd1349677e600d9259cbe07953c39ad7af6773)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/294110/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d71d0dea3d1658721b0a44ceeea8f4f12dada133 into 945532430284270631b092267ad77a06a0f046a2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/294111/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d16f48970d0f4d10faf0abc4e185c1876354f46e into 945532430284270631b092267ad77a06a0f046a2)

**Pull request merged**
