### PR TITLE
replaced string "rmt-migration" with "rmt-server-migration.service"

### PR DESCRIPTION
**Pull request by s-leon**
- replaced "systemctl start rmt-migration" with "systemctl start rmt-server-migration.service" (see [bug](https://bugzilla.suse.com/show_bug.cgi?id=1136165))

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/7426/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e7b58e44d155899bce01a9471888d0e504e16eab into ec94fd703037f0d3c9ca3147e18c7d0ecd1f252e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/7439/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e7b58e44d155899bce01a9471888d0e504e16eab into 5eea3c8aa458edef120a0376e439cdc4d5e90320)

**Comment by Sergeykot** [comment]
sorry @thutterer  did not see your review comment :no_mouth:

**Comment by s-leon** [comment]
As discussed in Standup: changelog entry not needed here.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/9125/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9e14317f5551937b620374bf20e4c759105a99ce into 5eea3c8aa458edef120a0376e439cdc4d5e90320)

**Pull request merged**
