### PR TITLE
Only include package/files and not package/obs in release tarball

### PR DESCRIPTION
**Pull request by digitaltom**
## Description

Drop unneeded directory from release tarball.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/221987/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into e30273fcb614dc9ea2561a4d2a903122f5669f3b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/222100/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into a5a6058122926185a1cad7ee304b25605cc6e5e2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/222894/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into ab2f86dfca9bb0b396330b3b9fc1e312afb137a9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/222972/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into f18462d3f067ea668d379b721adf50b3b98b4d01)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/223219/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into 8b58704ad3424243b5eb0a8d0e578ffc00b84929)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/223220/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into 99ecfcafba56cd2ec4e0ac346c7ea53da9e3ef27)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/225040/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e9241840bc627ac90c20bb797b2ea1f0735b4843 into ff95218f8ade55fad32fe1fa7e13a7e5d6ec0a50)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/225335/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4f0f5109e0ed5025c7c1f590cfbcec9cd57eaa8c into ff95218f8ade55fad32fe1fa7e13a7e5d6ec0a50)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/225336/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 4f0f5109e0ed5025c7c1f590cfbcec9cd57eaa8c into c90fc6c26f3b2c2317c875dc501dc40069335a1f)

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

** How I reviewed this pull request: **

- Checked that all required files are still copied
- Build the rpm package to see building working
- Installed the rpm to check nothing is missing

**Pull request merged**
