### PR TITLE
Don't fail the %post script which reloads nginx config if nginx is not running

### PR DESCRIPTION
**Pull request by digitaltom**
## Description

Please describe your change and provide as much context as possible.

Fixes https://bugzilla.suse.com/show_bug.cgi?id=1195759

## Change Type

*Please select the correct option.*

- [x **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/236669/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged bef558f43b1fc006d3915c58984fe6e3e4d8df61 into 5ea30405fee70f1ea5de0282bff6130675603185)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/236677/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged bef558f43b1fc006d3915c58984fe6e3e4d8df61 into 5ea30405fee70f1ea5de0282bff6130675603185)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/237191/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged d1f7036adab283eb348060d7002616a726283bfe into 5ea30405fee70f1ea5de0282bff6130675603185)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/237193/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d1f7036adab283eb348060d7002616a726283bfe into 5ea30405fee70f1ea5de0282bff6130675603185)

**Review by felixsch — APPROVED** [review]
lgtm :+1:

Note: I'm wondering if there is a `$service_` hook to do the reloading? Couldn't find one though.

**How I reviewed this pull request:**

- built the rpm package to see it working
- Checked the documentation about `try-reload-or-restart` to see potential side-effects

**As always if you think I'm missing something I should test, please let me know!** :rocket:

**Pull request merged**
