### PR TITLE
Fix local import of packages with special characters

### PR DESCRIPTION
**Pull request by digitaltom**
## Description

Fix local import of repositories containing packages with special characters in file name. For example '^', see https://bugzilla.suse.com/show_bug.cgi?id=1213002

This is the case for PackageHub 15SP5, package app-builder-3.4.2^20220309g4e2aa6a1-bp155.1.15

How to reproduce using a test repo: 

```
mkdir public/test; 
mkdir tmp/export; 
# make test repo available
cp -r spec/fixtures/files/dummy_repo public/test/
rails s &
bin/rmt-cli repos custom add http://localhost:4224/test/dummy_repo/ dummy_repo
bin/rmt-cli mirror
# export data
bin/rmt-cli export data tmp/export
bin/rmt-cli export settings tmp/export
bin/rmt-cli export repos tmp/export
# import data
bin/rmt-cli import data tmp/export
# this command will fail on master, and is fixed with this branch: 
bin/rmt-cli import repos tmp/export
```

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/322244/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 6bf15cd40d55a275e9330ed749fa30d19eb4fd74 into fe2c583173c896d6c522c3b18fbb6b802e9559b9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/322245/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 863a3aaab1f84c70eacb5e54f53ce47a784d5c99 into fe2c583173c896d6c522c3b18fbb6b802e9559b9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/322246/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ff0a3a235f31ccb8470ec20c793a695e6c859031 into fe2c583173c896d6c522c3b18fbb6b802e9559b9)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Review by felixsch — APPROVED** [review]
lgtm :+1: 

**How I reviewed this pull request:**
- Checked the code for changes I would suggest
- Created the test repo with apples and oranges and export/imported the repo to check everything is working correctly

**As always, if you think I missed something I should test, please let me know!** :rocket:

**Pull request merged**
