### PR TITLE
Make smt-data-import faster

### PR DESCRIPTION
**Pull request by ikapelyukhin**
Currently it's insufferably slow, which is an issue for 0-downtime SMT -> RMT migrations.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          3 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>bin/rmt-data-import</td>
      <td>4</td>
      <td>Layout/LeadingCommentSpace: Missing space after <code>#</code>. (https://github.com/bbatsov/ruby-style-guide#hash-space)</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>lib/rmt/cli/smt_importer.rb</td>
      <td>67</td>
      <td>Style/CommentAnnotation: Annotation keywords like <code>FIXME</code> should be all upper case, followed by a colon, and a space, then a note describing the problem. (https://github.com/bbatsov/ruby-style-guide#annotate-keywords)</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false"><table>
  <tbody>
    <tr>
      <td>lib/rmt/cli/smt_importer.rb</td>
      <td>170</td>
      <td>Layout/LeadingCommentSpace: Missing space after <code>#</code>. (https://github.com/bbatsov/ruby-style-guide#hash-space)</td>
    </tr>
  </tbody>
</table>
</td>
    </tr>
  </tbody>
</table>
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/355/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 0d7f26757c50886f23eca16621daba1003910617 into ebad8e102bb39d29e13189ee28ca9afa18cfe62f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/365/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 0d7f26757c50886f23eca16621daba1003910617 into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/371/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 051582c6c32bda7b3da49121308469b7ebba11f0 into b69d73c809c3ed9956a9466543529c70fbdb47f9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/372/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 051582c6c32bda7b3da49121308469b7ebba11f0 into ba2ca366d7996c5d6be42b20e3203e1d3bdce2dd)

**Comment by ikapelyukhin** [comment]
@fschueller I've bumped up the version.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/1468/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8d1772427443f26a79bf21a62c02e329fa787d22 into ba2ca366d7996c5d6be42b20e3203e1d3bdce2dd)

**Pull request merged**
