### PR TITLE
Move to GH Tokens for Prophet

### PR DESCRIPTION
**Pull request by tmuntaner**
## Description

Github is deprecating usage of its API by password authentication, so we need to move to token authentication.

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [x] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/137250/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged dee705303a9ee2a1374b0d2d38c1194d674e09d0 into 75e165cad616377e0d779abca82af77752146df5)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/137286/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged dee705303a9ee2a1374b0d2d38c1194d674e09d0 into f010687a6f9ec117811e3ed892cd509339b0a705)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
