### PR TITLE
use drop-in nginx configuration files

### LINKED ISSUE #631: nginx default config claims entire nginx instance
It seems there is no easy way to hook into nginx once `rmt-server-config.rpm` is installed.

With apache and SMT is was as easy as this:
````apache
Alias /urlpart "/path/to/my/urlpart"
<Directory /path/to/my/urlpart>
  <IfModule !mod_access_compat.c>
    Require all granted
  </IfModule>
  <IfModule mod_access_compat.c>
    Order allow,deny
    Allow from all
  </IfModule>
  Options       +Indexes +Multiviews +FollowSymLinks
  IndexOptions  FancyIndexing   ScanHTMLTitles  NameWidth=*     DescriptionWidth=*
</Directory>
````

With nginx such things are not possible, especially with `listen 80   default` in `/etc/nginx/vhosts.d/rmt-server-http.conf`.

It is possible to do something like `ln -s /path/to/my/urlpart /usr/share/rmt/public/urlpart`. But this will only work reliable when `http://host/urlpart/` is used as URL. With `http://host/urlpart` an `index.html` is loaded, but every image referenced in this website is loaded as `http://host/filename` instead of `http://host/urlpart/filename`.

In addition it is not possible to browse `/urlpart` in case no `index.html` exists.

I'm not familiar with `nginx`, or `apache`. It seems the only way to really hook into `rmt-server-config`, the provided nginx config files need an `include rmt-hooks-http.d/*.conf`.

### PR DESCRIPTION
**Pull request by olafhering**
Fixes #631

Signed-off-by: Olaf Hering <olaf@aepfle.de>

## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [x] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/183802/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/183914/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into bd51887f819592d95ee624b9baff5c1b9c88c898)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184060/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into 2f3ec01812a78a6347efe45c183b1f6ab1d417ca)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184105/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into 0aeb5c6fab7f7cde97e4fd59ff030b3fccfe59de)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184203/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184362/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into 57c3e24d3da0e80b114e74bfb86842e218b2f7ff)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184363/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into fec62a0d6c4adf73863ad1ad841abef1a8e6c4ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187263/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into c9a2c0a25899c58917d216fb150094001d39fb0b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187333/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into 05412b52a3cbaf2f3886fe77f84685d3f71aee40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187335/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into 9502b3b8b05e8c8cdfc60a0407605bde36495a36)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 60dd42ac9d27aee46a74730588862d3c801993bc into 263421b2813012775fb532fc8a8c4a59b1a6a68d)

**Pull request closed without merging**
