### PR TITLE
WIP: Add mysql ssl connection

### LINKED ISSUE #1016: SSL configuration settings support for database settings in `/etc/rmt.conf`
There does not currently seem to be a way to connect to a (MariaDB) database over SSL when using `rmt-cli` to perform repository syncing, mirroring, etc.

For example, the following command produces an error that only occurs when the database user provided in `/etc/rmt.conf` requires SSL:

```bash
$ bin/rmt-cli repos list
Cannot connect to database server. Ensure its credentials are correctly configured in '/etc/rmt.conf' or configure RMT with YaST ('yast2 rmt').
```

Checking the database logs confirms that the connection is not being attempted over SSL:
```[ERROR] Authentication requires SSL encryption.```

The [version of the `mysql2` adapter](https://github.com/SUSE/rmt/blob/fe2c583173c896d6c522c3b18fbb6b802e9559b9/Gemfile#L9) used does support [SSL configuration options](https://github.com/brianmario/mysql2/tree/0.5.3#ssl-options) that would allow for connections over SSL. 

However, these are not able to be set under the database settings in [`/etc/rmt.conf`](https://github.com/SUSE/rmt/blob/fe2c583173c896d6c522c3b18fbb6b802e9559b9/config/rmt.yml#L5-L14), or at least they don't seem to be used:

https://github.com/SUSE/rmt/blob/fe2c583173c896d6c522c3b18fbb6b802e9559b9/lib/rmt/config.rb#L17-L28

Is this understanding correct, or is something being done wrong?

Side note from testing: The [`mysql_clear_password.so` plugin library](https://mariadb.com/kb/en/authentication-plugin-pam/#client-authentication-plugins) may be required when connecting over SSL.

### PR DESCRIPTION
**Pull request by ngetahun**
## Description

Fixes #1016 

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/348082/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 8d4670dd2a7e31007d16cd1519e9f9ade3698e0a into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/348776/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 803d2b255cb03f78b6f794e567510d87df12a9e5)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/351235/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 7e68170344b9747f53da348fea62e2668c3f2aee)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/351423/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 56477e726b7417f423f03cbc23ab8d5febc3b400)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/351441/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 40dd490a960f56cb2b641696bf5495eace3a8a7d)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/351584/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 9f151f09811d94f59cf11460b814f1faa2f193c8)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/351594/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 4926fb902d3e9c4583c4251415585c8cad14c22f)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/352701/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 5d088748922b5bc6be802d0c895fe08c45cfd904 into 91457227b05f9b2e7b124f0934f2008e32a9c4e0)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/353937/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 7b35b29b244d2cf1d193b943a4b18157cae63722 into 91457227b05f9b2e7b124f0934f2008e32a9c4e0)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/355893/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images.
Failed fast in project rmt on step docker-compose-build-images. (Merged 627a3daebff7f35d29af3fc1c4306a9803e9ec6c into ecf5efb3d9dbfce20f8d302a5ae4db03e08f611d)

**Comment by felixsch** [comment]
tracked here: https://trello.com/c/i9iUF8hT/5089-rmt-support-ssl-encrypted-mariadb-connection

I close this for now until we find time to progress further!

**Pull request closed without merging**
