### PR TITLE
Update PACKAGE.md

### PR DESCRIPTION
**Pull request by wstephenson**
Add additional guidelines about correctly describing CVEs in changelog entries for maintenance requests.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/5684/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d94daac57426213cfa042690be47919334325b32 into 001e15760d5e3796128f54d63e495ccdd2fe3b43)

**Comment by ikapelyukhin** [comment]
@wstephenson please commit the updated RPM spec file into the repo.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/5721/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d94daac57426213cfa042690be47919334325b32 into 6ee70a806ae43e81e8c77ae2462435dd48f879c7)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/7426/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d94daac57426213cfa042690be47919334325b32 into ec94fd703037f0d3c9ca3147e18c7d0ecd1f252e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/7439/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d94daac57426213cfa042690be47919334325b32 into 5eea3c8aa458edef120a0376e439cdc4d5e90320)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/9128/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d94daac57426213cfa042690be47919334325b32 into 326723a1245ff00759cb7acc305bfc688ba2babc)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/9691/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged d94daac57426213cfa042690be47919334325b32 into d69f8b81a1f55ab7bc3df55379e077058cadae4b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/9692/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into da1ecfa8fe2b904e3acad95ac0992584135f1306)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/10433/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into 3af3aeb1c392fb7e6c61b808ef3d368768b70436)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/10434/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into cd1f46cfa681f91eca7aed9b46bd64966a1d77d2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/10446/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into 0fcc532cd6d7b517cd03f883b585cfc5659c5452)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/10447/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into 7553c206aa57cf337573648dfae47e4e49469521)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/13007/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into f06fa3c8d156af25e5bac0eb8afd66ef719d8921)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/15331/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into 0f0459635cd7756df430ae881b79a8bdabe96a29)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/16422/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged b05503b537742ddde337cdaa92ead714e02eb7a3 into f4541f3c3ebd0748cbc9855eeb809e1b7efc84b1)

**Pull request merged**
