### PR TITLE
Revise obs changelog

### PR DESCRIPTION
**Pull request by ngetahun**
## Description

Please describe your change and provide as much context as possible.

Fixes # (issue)

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [x] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ ] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ ] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [ ] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231776/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e2433d6fc95647ed95813674a6525c633839421d into 62e114830c657a2bbfb31937658f417267316861)

**Review by mssola — APPROVED** [review]

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231898/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e2433d6fc95647ed95813674a6525c633839421d into d487fbb1c8558fcc13e137be8793d041c02ee199)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231899/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3f40e8bd54fefceb671d787a9deab4c45c1d4e43 into d487fbb1c8558fcc13e137be8793d041c02ee199)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231915/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 21f370f59fb67cf2d00e16277c9b946749c782bb into d487fbb1c8558fcc13e137be8793d041c02ee199)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/231921/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a34593b68ab5f32bb2321a8c5eca0fbda547a5ee into 9dd978122d9b41675b3cff2943beaed4b7c142f6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/234253/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 9ecad49e5aa1183d6053ee0cc240bb772146dbdd into 9dd978122d9b41675b3cff2943beaed4b7c142f6)

**Pull request merged**
