### PR TITLE
Update instance verification example

### PR DESCRIPTION
**Pull request by jesusbv**
## Description

Update instance verification example.rb

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)
- [X] **Example Update**

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [X] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/171822/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into db4e77ddac635da9c1d35b0464afbf81550fb257)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/174671/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 4bebacb3abda3fbf1562f6cdaf606551d5568705)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/175712/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 920de39c1791930669c5dff8a5c9312c82b45750)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/176363/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into f33b1166afafc06baaf402e40da01c3f9c56e435)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/183914/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into bd51887f819592d95ee624b9baff5c1b9c88c898)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184060/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 2f3ec01812a78a6347efe45c183b1f6ab1d417ca)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/184061/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 023f61747d6a2b527cbc0ac4f0a83d9845a423a3)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184105/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 0aeb5c6fab7f7cde97e4fd59ff030b3fccfe59de)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184203/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into b647997301d9366250e0e204efb300c8cd74e7d4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184362/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 57c3e24d3da0e80b114e74bfb86842e218b2f7ff)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/184363/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into fec62a0d6c4adf73863ad1ad841abef1a8e6c4ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187263/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into c9a2c0a25899c58917d216fb150094001d39fb0b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187333/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 05412b52a3cbaf2f3886fe77f84685d3f71aee40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187335/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 9502b3b8b05e8c8cdfc60a0407605bde36495a36)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/187419/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 263421b2813012775fb532fc8a8c4a59b1a6a68d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/187453/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into e7110f4096c8c8d2543dad907879adb25fd98b76)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/188037/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by digitaltom** [comment]
Hi @jesusbv, is this pr still wanted? It would need a review from somebody from the public cloud team.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189696/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 771f28783396c9e4a5478bbf3825154110e96d86)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189697/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 4e784eb993d81d59161441fe6d3e4a26245e3f8b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189796/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 1fca334f0cd1b32d552e9e624754dce37c7a98ec)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189814/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 0c531f2ba87b5d1e61d17d0e6698a31a9218faf2)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189815/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 66c932025b24208ac1610fcb7f6672c482175e72)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/190433/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 1264a26e24ef05b70b1362b6527855e80465684a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/191477/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 7a4d4c97b94733170f33e2f93655aae047eb381e)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/192085/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 6da51f61d7bf2a6cea0e9b937222c795da9cbb9a)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/193772/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 55ce6a2480f8c17518611a3adc3b27a384ba0e40)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/193906/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 71386fd62b5658eb00ae2881b8a9b8b12ae1e83c)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/193939/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 177d406d9bef02b09b73ad13731a94aa2c20ef6a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/193940/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests.
Failed fast in project rmt on step docker-compose-run-tests. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 43c9eed40cfe99dd2456bcf4d185671c153e5127)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/194401/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 81b807b61c9aa283f10d80dd7a52d2dd36543ad9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/194907/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 8a5f2553e0709b680233f21ee3ff26be409956e0)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/195186/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 9c6abc816a72e4c5601cb8202682f2d2e54cea4b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/195205/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f5d6be655d6bccfa61a0f319a69fc19e16417413 into 87995122e3d01d8d0a57e140c4079f36ad327a2d)

**Review by digitaltom — APPROVED** [review]
@jesusbv ping.. This pr is only touching the `instance_verification` code, so it's fine for us. You might want to have someone from your team to look over it? Feel free to merge it.

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/195330/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 67ed650f23d60912824fdcd395ee1ff83f3ced68 into 87995122e3d01d8d0a57e140c4079f36ad327a2d)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/196701/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 67ed650f23d60912824fdcd395ee1ff83f3ced68 into 707f3a5bb8b0cfc6f11b862f8e0ce94a1902c24c)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/196711/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 67ed650f23d60912824fdcd395ee1ff83f3ced68 into 7504190fc39c54207261f6d8dc851691ced6ab4b)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/198368/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 67ed650f23d60912824fdcd395ee1ff83f3ced68 into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/198521/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3a22b526e17b246fb3f5b33f4bd4941034a6ce02 into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/198900/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 0c54501969c0ebe10145f99887e1cbcb73373a0b into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/199993/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged a9973241c768c1d30177a76b7fad7a2863b7220f into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/199997/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 7cb9c50a2cd76f477163c475ac2e7155615154ee into bc06fd9f011ddf1959b0e472c44c868c72ea22ee)

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger-pr">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/202269/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 3c968c3fd25eb077c54f182567800bcab588c7e5 into 9228f9da8667575db38b9cab33b6596cf035a340)

**Pull request merged**
