### PR TITLE
Fix mirroring installer-updates repos by default

### PR DESCRIPTION
**Pull request by jesusbv**
## Description

The fix for #554 (and later issue #607) was misplaced.
It marked the installer-updates repos in the wrong place.

This fixes that (both issues) and adds the proper enabling in the right place.

This references bsc#1184814

## Change Type

*Please select the correct option.*

- [X] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [X] I have verified that my code follows RMT's coding standards with `rubocop`.
- [X] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [X] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

## Other Notes

Please use this space to provide notes or thoughts to the team, such as tips on how to review/demo your changes.

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189302/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 16c75e0503817c9b141ba7e7ba166f63c0ae4f16 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189345/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 16c75e0503817c9b141ba7e7ba166f63c0ae4f16 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Review by ngetahun — APPROVED** [review]
LGTM!

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189564/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 16c75e0503817c9b141ba7e7ba166f63c0ae4f16 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/189566/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 16c75e0503817c9b141ba7e7ba166f63c0ae4f16 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189682/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 16c75e0503817c9b141ba7e7ba166f63c0ae4f16 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/189690/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 5c06954c52e0cdd3281edabb99273889e8da5375 into 88cf7643c4acc63275659c5cd57281afdd2804ae)

**Pull request merged**
