### PR TITLE
Don't create suma and repo symlinks at install stage

### PR DESCRIPTION
**Pull request by Alix82**
## Description
Don't create suma and repo symlinks at install stage
instead, only link them at the post stage if they don't exist. This
permits to change the default location of the mirrored repository and so
it is not overwritten on update or re-install of rmt-server package.

See bsc#1188043 for more details.

## Change Type

*Please select the correct option.*

- [x ] **Bug Fix** (a non-breaking change which fixes an issue)
- [ ] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [ x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [ x] I have reviewed my own code and believe that it's ready for an external review.
- [ ] I have provided comments for any hard-to-understand code.
- [ ] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x ] RMT's test coverage remains at 100%.
- [x ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.

### CODE REVIEW

**Comment by ngetahun** [comment]
@Alix82 Can you rebase your branch with origin master? We have added github actions config.

**Comment by felixsch** [comment]
Hi Alix82, thank you for the contribution!

I build the rmt package from your branch and it works fine. lgtm :+1:

Can I ask you to resolve the branch issues and add your Changelog entry. There will be a release soon!
Thank you very much!

**Comment by felixsch** [comment]
Oh I saw the 2.6.11 is not yet released. You could also add your changed to this version that we don't step over one version :) While doing this I try to find out whats wrong with the github actions...

**Comment by Alix82** [comment]
There are still some issues with the merge?

**Comment by digitaltom** [comment]
This seems to depend on https://github.com/SUSE/rmt/pull/751 to have the CI green.

**Comment by Alix82** [comment]
This is still not merged, could be please merge it asap? Thanks!

**Review by ngetahun — APPROVED** [review]
LGTM!

**Pull request merged**
