### PR TITLE
Accepting contribution from Factory maintainer regarding systemd.

### PR DESCRIPTION
**Pull request by digitaltom**

### CODE REVIEW

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89494/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c13d677bf290f0d5cff425acf39f502006a66eb9 into dd0c0a37502c02934cc12f4274657eee425243b8)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89507/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged c13d677bf290f0d5cff425acf39f502006a66eb9 into dd0c0a37502c02934cc12f4274657eee425243b8)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89508/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 6004110528fad8119139af6fe2b8e7e54bbc361a into c3ff5a09af66cf2f786861cd32bdc91f51670590)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89516/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 6004110528fad8119139af6fe2b8e7e54bbc361a into c3ff5a09af66cf2f786861cd32bdc91f51670590)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/89533/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 6004110528fad8119139af6fe2b8e7e54bbc361a into 2b366f5325b0cfe1cd4ee43c9bc77d7b5b3526a6)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/89541/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 1b85c8b931c4ffef009ac465d5a7ed27110d5465 into 2b366f5325b0cfe1cd4ee43c9bc77d7b5b3526a6)

**Pull request merged**
