### PR TITLE
Add instance_data and system_information table to systems and provide cloud_provider accessor

### PR DESCRIPTION
**Pull request by felixsch**
## Description

In our efforts to make data structures more simple and more generic we trying to remove the HwInfo column from RMT and replace it with a JSON/TEXT column to make more dynamic and more easy data handling possible.

This is the first pull request adding the required columns and the `cloud_provider` accessor which lenses into the stored JSON.

## Change Type

*Please select the correct option.*

- [ ] **Bug Fix** (a non-breaking change which fixes an issue)
- [x] **New Feature** (a non-breaking change which adds new functionality)
- [ ] **Documentation Update** (a change which only updates documentation)

## Checklist

*Please check off each item if the requirement is met.*

- [x] I have verified that my code follows RMT's coding standards with `rubocop`.
- [x] I have reviewed my own code and believe that it's ready for an external review.
- [x] I have provided comments for any hard-to-understand code.
- [x] I have documented the `MANUAL.md` file with any changes to the user experience.
- [x] RMT's test coverage remains at 100%.
- [ ] If my changes are non-trivial, I have added a changelog entry to notify users at `package/obs/rmt-server.changes`.
=> This will come when the whole migration from `Hwinfo` to `System.system_information` is done.

## Other Notes

SUSE tracking card: https://trello.com/c/4geTYoLN/2931-cmdrmt-create-new-required-backend-attributes-to-store-hardware-information-transparently

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/323244/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f3f36dca17c7042f14a6bcba0c39e9b011d31cdc into fe2c583173c896d6c522c3b18fbb6b802e9559b9)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/323245/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged f1a3be998e20c09fad55ae2ce28b99d60699f68b into fe2c583173c896d6c522c3b18fbb6b802e9559b9)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/323284/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 08741f09222060ec52e84f868804a4e53fe18da7 into e88e8d75cb85968c1b42983fc4595afab5b64850)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/323392/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged 08741f09222060ec52e84f868804a4e53fe18da7 into e88e8d75cb85968c1b42983fc4595afab5b64850)

**Pull request merged**
