### PR TITLE
Cleanup docker of RMT integration tests related things

### PR DESCRIPTION
**Pull request by Sergeykot**
The old way of cleaning docker system did not work and was leaving docker images after test run.

Let's cleanup it properly after each run of the tests

### CODE REVIEW

**Comment by suse-tests-pass** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Unless this is a trivial change, please include a CHANGELOG entry.<br />
Run <code>osc vc</code> in the <code>package</code> directory to add one.</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89515/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-run-tests. (Merged 027a09f60d5043ee539227422f388245110cf675 into c3ff5a09af66cf2f786861cd32bdc91f51670590)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/89533/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-system-cleanup. (Merged 027a09f60d5043ee539227422f388245110cf675 into 2b366f5325b0cfe1cd4ee43c9bc77d7b5b3526a6)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/90268/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-system-cleanup. (Merged e99cb5fc538fdcec7062f3fea38ffcddd4f8ed61 into da6003e517c9024e1bab1424166889d59508902a)

**Comment by suse-tests-fail** [comment]
Prophet reports failure.
https://ci.suse.de/job/scc-RMT-integration-tests/90284/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment.
Failed fast in project rmt on step docker-compose-system-cleanup. (Merged e99cb5fc538fdcec7062f3fea38ffcddd4f8ed61 into 59a541f122d469a96e4f6cbdce2d8ccaa3c64db4)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/90286/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged e99cb5fc538fdcec7062f3fea38ffcddd4f8ed61 into a72b62555263d9e465e0e3bf33f5ea85a1597520)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/90287/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged eaa1a216f39080cf596576d63c6eabcc4055a86e into a72b62555263d9e465e0e3bf33f5ea85a1597520)

**Comment by suse-tests-pass** [comment]
Well Done! Your tests are still passing.
https://ci.suse.de/job/scc-RMT-integration-tests/90289/console
If the given link has expired,you can force a Prophet rerun by just deleting this comment. (Merged ac965a828238bf825e137cdf294dd1ff744427eb into 2ac6cdd6144ddc31d7c0d4c41c1a8e965adefa1c)

**Pull request merged**
